const { detectContributingFactors } = require('./src/utils/rootCauseEngine.js');

// BBS Observations in Site Security (74 observations)
const bbsObservations = [
  "Site security gate was broken.",
  "During the time visit, it was observed the ALHARBI provided a proper security guard at the site.",
  "It was observed that the security barrier was left open and not closed by the security guard during working hours.",
  "During inspection, drill machines were found stored in the security cabin instead of the designated storage area, creating potential hazards and obstructing the cabin space.",
  "It was observed that security personnel are still not present at the site during the working hours.",
  "At the site, the security stopper barrier was found left open, creating a potential risk of unauthorized access and compromising site security.",
  "Security guard is without NEOM ID",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Demarcation found done at site security entrance road for easily identifiable TDP site and to prevent unauthorized entry.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "First Aid kit found provided in site security cabin.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Good practice observed an operating security camera in the security cabin",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Observed that the security guard checking at the security point on the entrance",
  "Following security observations were observed:- 1) Arm barrier at security cabin not Installed. 2) AC unit at security cabin is not working as no generator installed 3) the Generator was unservisable , so the CCTV camera was also not working . TV not installed to see those on screen. 4) Toilet inside the security cabin is not clean also no water and soap provided, exhaust fan not working. 5) Flood light at security cabin not provided and no generator for connection yet. Contractor is advised to rectify these issues",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Security - Site entrance gate kept open and security guard not in vicinity allowing unauthorized site entrance",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "No means of safe access/egress provided for security cabin",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "It was observed that site security gate was properly segregated by concrete barriers at the entrance",
  "Provided security cabin not functional; no power supply; arm barrier, CCTV camera not installed, assigned security person is not competent, and security guard cabin not protected. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (not limit entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7). Contractor shall ensure that guard cabin shall protected with hard barriers and install speed hump to breakdown and control the vehicle speed.",
  "First aid training provided to the security guards",
  "Contractor failed to comply Security Schedule S. Local Saudi guard not hired, CCTV system not functional, first aid kit and fire extinguisher not provided, grounding not installed for security cabin at main entrance towards GCS site. Workplace not protected from unauthorized entry at Aljaber working side. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (Saudi security guard, entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7). Ensure first aid kit, fire extinguisher, grounding shall install and ensures CCTV shall ensure functional and shall maintain record for 60 days. Ensure that workplace secured all sides to prevent unauthorized entry to worksite.",
  "site security cabin protected with hard barricades",
  "The security guard with face recognitions device at the entrance of the site",
  "The security guard at site security check point ,controlling the exit, entry for the authorized employee .",
  "Duties and responsibilities of security Guards",
  "security guard available at security gate 24/7.",
  "Site operatives were found working without NEOM ID.",
  "During the route visit it was observed at site security guard is available and alert and arm barrier is closed to restrict unauthorized entry.",
  "Security Log sheet available at security guard house at site.",
  "The security guard at site entrance ,recording entrance and exit of employee ,stopping unauthorized entry .",
  "CCTV system not functional at main entrance of ISF workplace. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (Saudi security guard, entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7) and ensures CCTV are installed on entrance and exit and shall maintain record for 60 days.",
  "New generator for security cabin provided to restore electricity at site security cabin",
  "It was observed that power supply not provided to the security guard cabin at ISF site entrance. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (not limit entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7). Ensure power supply provided.",
  "CCTV Camera at office area security cabin operational , the screen monitoring by security guard",
  "Site security instructions and SOP's available in English and Arabic not available. Ensure that site security instructions and SOP's available in English and Arabic at both entrances.",
  "it was observed that security guard regularly drop arm barrier to restrict unauthorized entry to site",
  "It was observed that a security was seen at the entrance of the site",
  "It was observed that a security guard was seen checking at the entrance of the site",
  "No available security personnel while the area is accessible to outsiders. Ref: NEOM PHSAS 37.4 Security and Site Access Control Contractors must establish suitable site demarcation hoarding / fencing to prevent unauthorized access to work areas complete with separate pedestrian and road access points. Guard houses and security personnel plus a physical barrier must be provided for each access gate and will be manned by each Contractor's designated security service from a NEOM-approved provider.",
  "It was observed that a security guard was available at the entrance of the site",
  "It was observed that a security cabin had the availability of neom emergency contact numbers and TDP Emergency contact lists. Suggested ideas : Made sure that security personnel are informed about the emergency contact numbers",
  "It was observed that a security guard was seen at the entrance of the site",
  "During the site inspection, it was observed that there were no security personnel present at the entrance gate. This absence of security personnel presents a significant risk, as it leaves the site vulnerable to unauthorized access, theft, or potential safety breaches.",
  "It was observed that there was a security guard checking the entrance of the site",
  "It was observed that a security guard was seen checking at the entrance of the site",
  "Security personnel were not present at the security cabin during the inspection, leaving the gate open and allowing several vehicles to pass through without being checked. Ref: NEOM PHSAS 37.4 Security and Site Access Control Contractors must establish suitable site demarcation hoarding / fencing to prevent unauthorized access to work areas complete with separate pedestrian and road access points. Guard houses and security personnel plus a physical barrier must be provided for each access gate and will be manned by each Contractor's designated security service from a NEOM-approved provider.",
  "The air conditioning in the security cabin at Area 3 gate is not functioning, causing discomfort for the security personnel. This could affect their focus and performance, impacting overall security effectiveness.",
  "In the early morning of April 2nd, during the Eid Al-Fitr holiday, a theft occurred at the HIDC 2 warehouse. The perpetrators gained unauthorized access by cutting two openings in the warehouse temporary perimeter fence: The first opening was made near the tkSAC warehouse area. The thieves cut through 1 section of the fence, but no items were stolen from this side. The second opening was made near the subcontractor's (TCC) warehouse / storage area, where they cut through three sections of the fence. The thieves break the installed locks and forcibly entered the TCC warehouse and stole the listed materials below. They also attempted to break into two small doors belonging to tkSAC on the southern side of the warehouse. Although the locks were forced open, nothing was stolen from inside. Investigations confirmed that the thieves used a vehicle to transport the stolen items. The southern side of the warehouse was identified as the main entry and exit point. The incident was not detected by the night shift security guards or the Zone A gate security personnel. It was also confirmed that the thieves did not enter through the main gate.",
  "During a routine site inspection, it was noted that site security personnel were not present at their designated post during scheduled duty hours. This absence compromises site safety increases the risk of unauthorized access, theft, and delayed emergency response.",
  "During a routine site inspection, it was observed that no security personnel were present at the site entrance or perimeter, as required by site safety and security protocols.",
  "It has been observed that the roof of the site security cabin is damaged, potentially allowing water ingress and weakening the structure. Additionally, the floor is constructed using only plywood panels, a material that is highly flammable and susceptible to damage from moisture, physical wear, or fire.",
  "CCTV cameras at the site are operational and providing proper surveillance coverage. This enhances site security and helps in monitoring activities for safety compliance.",
  "It has been repeatedly observed that the site security cabin lacks several basic safety and functional requirements, including: Absence of a seamless floor sheet – current flooring poses a trip hazard and may accumulate dust or water. Inadequate furniture – the cabin does not have a proper table and chair with cup slots/holders, affecting comfort and functionality. Damaged roof – visible leaks and structural wear may expose personnel to weather and injury risk.",
  "During the morning site inspection, it was observed that the work team failed to establish an exclusion zone around an active work area. This could allow unauthorized personnel to enter the hazardous zone, increasing the risk of incidents such as falling objects, equipment strikes, or other unsafe interactions.",
  "The site security cabin was found to be in poor condition. The cabin was unclean, and the furniture (chair and table) were damaged and still not replaced despite previous reports. In addition, there is no electricity supply in the cabin, creating inadequate working conditions for security personnel.",
  "It was observed that the CCTV cameras at the site security cabin are currently unserviceable. This compromises the site's overall security monitoring and incident response capability. Ref: NEOM-NPR-STD-001 - Projects Health and Safety Assurance Standards, Section 37.4: Security and Site Access Control.",
  "During the site inspection, it was observed that the security log sheet was not updated and was found in an outdated status. This compromises the accuracy of access control records and weakens overall site security monitoring.",
  "On the site it was observed that the site security was not available at the site",
  "During a site walkthrough, It has been observed the contractor has Improved the site security gate and cabin.",
  "No Provision of site security, site fencing and associated gates and barriers (in accordance with security and safety directives) to prevent unauthorized entry of vehicles.",
  "No security guard seen on gate from SHAR side, this may lead to unwanted event in the terms of security of site, port, and materials stacked at site. Contractor is required to appoint a security guard on gate and entry log system at gate."
];

// Signage Observations in Site Security (52 observations)
const signageObservations = [
  "A damaged electrical socket was found inside the security cabin. The socket shows visible signs of wear, including cracks and loose fitting, posing a risk of electrical shock or short-circuit.",
  "During inspection, drill machines were found stored in the security cabin instead of the designated storage area, creating potential hazards and obstructing the cabin space.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Observed that zone identification signages are posted at side",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "It was observed that the security cabin near the entrance was being cleaned and provided with proper installation of signages.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Signages are found placed in adequate numbers near security area",
  "Found the signboard containing the availability of Emergency contact numbers near the security cabin",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Visitors sign in list was checked and all brackets filled with information.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Safety signage - STOP signage not installed on arm barriers at both security gates. Security arm barrier at site entrance not easily visible.",
  "There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "Observed the installation of signages at new security checkpoint HW55",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "[8:20 AM] Yousaf, Kamran [NN-SA] There are serious concerns about the security procedures at the TDP work site. During my visit today, I noticed that a truck with a denied access status could enter the premises and operate on the site. This is a clear breach of NEOM security protocols and poses a significant risk to the safety and integrity of NEOM operations. The fact that security personnel did not properly check the status of this truck and prevent its entry is unacceptable. NEOM implemented strict guidelines to ensure that only authorized vehicles and personnel are granted access to the site. Allowing unauthorized trucks to enter and work undermines the entire purpose of these security measures. I strongly advise that you take immediate action to address this issue. All trucks with a red status should be stopped and removed from the site without exception. Security personnel must be instructed to thoroughly verify the access status of every vehicle before granting entry. Maintaining a secure work environment is of the utmost importance. I trust that you will take the necessary steps to rectify this situation and prevent such breaches from occurring in the future.",
  "During the inspection of site it was observed that a signage was being placed at an adequate place at the security cabin.",
  "Stop and security check signages provided on the arm barrier of security gate at site",
  "Provided security cabin not functional; no power supply; arm barrier, CCTV camera not installed, assigned security person is not competent, and security guard cabin not protected. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (not limit entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7). Contractor shall ensure that guard cabin shall protected with hard barriers and install speed hump to breakdown and control the vehicle speed.",
  "Provided security cabin not functional; no power supply; arm barrier, CCTV camera not installed, assigned security person is not competent, visitors log sheet not maintained. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (not limit entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7).",
  "Sign boards installed near the fence gates",
  "Good display of signages at site and arm barriers closed to restrict unauthorized entry",
  "stop sign with barriers placed near the security gate of office to control the unauthorized entry in the office premises",
  "Security check point signages installed at office area to guide visitor and workers about the security check before entering into the project premises.",
  "Generators using as a power source to the security cabin prestart checklist not provided and ear protection signage not posted. Recommendations: Contractor shall ensure that a competent person shall inspect equipment and plant prior to use or operate it. Area Site Supervisor or area assigned safety officer shall ensure the availability. Ensure ear protection signage posted where required.",
  "Project signages posted at the front gate contain all the project details.",
  "Site Safety Informative signage posted with the security gate .",
  "CCTV camera installed, functional and assigned security person is trained and visitors log sheet maintained.",
  "During a routine site inspection, it was observed that a safety signboard and barricade had fallen down, creating a potential safety risk by reducing hazard visibility and access control",
  "During the inspection of security cabin it was noticed that a first aid box with the availability of first aid checklist was available",
  "No available security personnel while the area is accessible to outsiders. Ref: NEOM PHSAS 37.4 Security and Site Access Control Contractors must establish suitable site demarcation hoarding / fencing to prevent unauthorized access to work areas complete with separate pedestrian and road access points. Guard houses and security personnel plus a physical barrier must be provided for each access gate and will be manned by each Contractor's designated security service from a NEOM-approved provider.",
  "The spill kits have a checklist to ensure that the items are provided and sufficient, but there is a lack of inspector information (name and signature) for the current week, raising suspicion that an unauthorized person may have conducted the inspection that may result to not maintained properly. TKSAC-CMG-G000-BG-00001 OSH Construction Management Plan 13.4 Refueling and cleaning of construction vehicles Emergency spill kits shall be available. These spill kits should be maintained on a regular basis to ensure that they are always available and fit for purpose where permeable soils may be polluted.",
  "Signages placed near the DG of security cabin",
  "During the site inspection, it was observed that there were no security personnel present at the entrance gate. This absence of security personnel presents a significant risk, as it leaves the site vulnerable to unauthorized access, theft, or potential safety breaches.",
  "Security personnel were not present at the security cabin during the inspection, leaving the gate open and allowing several vehicles to pass through without being checked. Ref: NEOM PHSAS 37.4 Security and Site Access Control Contractors must establish suitable site demarcation hoarding / fencing to prevent unauthorized access to work areas complete with separate pedestrian and road access points. Guard houses and security personnel plus a physical barrier must be provided for each access gate and will be manned by each Contractor's designated security service from a NEOM-approved provider.",
  "During the inspection of the security cabin, it was observed that flammable material had been stored inside the cabin. This poses a significant fire and flammability hazard, especially in a confined space like the security cabin, potentially endangering personnel and property.",
  "It was observed on site that cement bags and other construction materials were placed near the security cabin, which is not a designated storage area for such materials.",
  "During a routine site inspection, it was noted that site security personnel were not present at their designated post during scheduled duty hours. This absence compromises site safety increases the risk of unauthorized access, theft, and delayed emergency response.",
  "On Thursday, May 16, 2025, at approximately 5:00 PM, Mr. Mahmoud Yousaf, who serves as the Construction Manager for the NEOM project, completed the operational use of a company-assigned drone. After concluding the activity, he returned to his office and securely placed the drone inside the drawer of his personal desk, located in his private office, which is normally kept open during non-working hours. Mr. Mahmoud then left the office for the weekend as per regular schedule. When he returned to work on the morning of Saturday, May 18, 2025, at around 7:20 AM, he proceeded to retrieve the drone. Upon opening the desk drawer, he was alarmed to find that the drone was no longer in its designated location. He immediately conducted a quick search within his office and the surrounding area but was unable to locate the missing item. Recognizing the potential seriousness of the situation and the value of the missing equipment, Mr. Mahmoud promptly reported the matter to the site's Security Manager and initiated a formal complaint to the local police authorities. The drone, which is a sensitive and high-value piece of project equipment, is vital to ongoing construction documentation and progress tracking activities. Its sudden disappearance raises serious concerns regarding office security, access control, and potential theft.",
  "The company logo stickers were placed on all vehicles observed to be engaged in site operations.",
  "A Horizontal Directional Drilling (HDD) machine was observed in operation without any physical protection or barricading around the machine or its working area. There were no barriers, caution tape, or signage to restrict unauthorized personnel from entering the danger zone.",
  "project sign board has been install in the main gate",
  "Unauthorized area was identified with the proper barricades and signage to restrict the unauthorized persons."
];

// Maintenance Observations in Site Security (31 observations)
const maintenanceObservations = [
  "Site security gate was broken.",
  "Generator supplying power to CCTV, Tower flood light is not working.",
  "observed elecrtical plug was broken in security cabin.",
  "Security - Unauthorized access to office premises not controlled. Exit/Entry log sheet not maintained. Security cameras not installed.",
  "A damaged electrical socket was found inside the security cabin. The socket shows visible signs of wear, including cracks and loose fitting, posing a risk of electrical shock or short-circuit.",
  "It was observed that the security cameras were not operational during the inspection, creating a gap in site monitoring and security.",
  "it was observed that toilet near security cabin: not properly maintained water hose are not working",
  "It was observed that the power supply was not available in the security cabin, resulting in the security cameras being non-operational.",
  "During inspection, drill machines were found stored in the security cabin instead of the designated storage area, creating potential hazards and obstructing the cabin space.",
  "CCTV - Observed that cctv cameras in the security cabin are working and are in good condition",
  "Maintenance truck found parked at site in unauthorized area.",
  "Following security observations were observed:- 1) Arm barrier at security cabin not Installed. 2) AC unit at security cabin is not working as no generator installed 3) the Generator was unservisable , so the CCTV camera was also not working . TV not installed to see those on screen. 4) Toilet inside the security cabin is not clean also no water and soap provided, exhaust fan not working. 5) Flood light at security cabin not provided and no generator for connection yet. Contractor is advised to rectify these issues",
  "Observed that security cameras are working properly",
  "During weekly walkthrough following Security deficiencies were observed:- a) Arm barrier at security cabin not Installed. b) AC unit at security cabin is not working as no generator installed c) the Generator was unservisable , so the CCTV camera was also not working . TV not installed to see those on screen. d) Flood light at security cabin not provided and no generator for connection yet. COntractor were informed of all noted points at site and advised rectify.",
  "During weekly walkthrough following Security deficiencies were observed:- 1) AC unit at security cabin is not working as no generator installed 2) the Generator was unservisable , so the CCTV camera was also not working . TV not installed to see those on screen. 3) Flood light at security cabin not provided and no generator for connection yet. Contractor were informed of all noted points at site and advised rectify.",
  "Provided security cabin not functional; no power supply; arm barrier, CCTV camera not installed, assigned security person is not competent, visitors log sheet not maintained. Recommendations: Contractor shall comply to Schedule S for security arrangement at workplace (not limit entry exit log, air conditioning security cabin with toilet, barrier/gate and is manned 24/7).",
  "CCTV system not operational at site entrance towards ISF area.",
  "During walkthrough, it was observed that access not controlled and unauthorized person can entry towards workplace at the offloading area.",
  "During walkthrough, it was observed that CCTV system installed at site entrance not operational.",
  "CCTV system installed at site entrance not operational, site entrance not controlled, unauthorized person entry towards workplace at the offloading area.",
  "It was observed that entry log sheet for confined spaced entry was well maintained by site personnel",
  "The spill kits have a checklist to ensure that the items are provided and sufficient, but there is a lack of inspector information (name and signature) for the current week, raising suspicion that an unauthorized person may have conducted the inspection that may result to not maintained properly. TKSAC-CMG-G000-BG-00001 OSH Construction Management Plan 13.4 Refueling and cleaning of construction vehicles Emergency spill kits shall be available. These spill kits should be maintained on a regular basis to ensure that they are always available and fit for purpose where permeable soils may be polluted.",
  "The step of the security cabin is not safe and not according to the standard.",
  "The water station located at the security cabin was found to be in an unclean condition, indicating a lack of regular maintenance and poor hygiene practices.",
  "An energized electrical panel was observed without a barrier to isolate it from unauthorized personnel or moving equipment.",
  "The air conditioning in the security cabin at Area 3 gate is not functioning, causing discomfort for the security personnel. This could affect their focus and performance, impacting overall security effectiveness.",
  "It has been observed that the roof of the site security cabin is damaged, potentially allowing water ingress and weakening the structure. Additionally, the floor is constructed using only plywood panels, a material that is highly flammable and susceptible to damage from moisture, physical wear, or fire.",
  "It has been repeatedly observed that the site security cabin lacks several basic safety and functional requirements, including: Absence of a seamless floor sheet – current flooring poses a trip hazard and may accumulate dust or water. Inadequate furniture – the cabin does not have a proper table and chair with cup slots/holders, affecting comfort and functionality. Damaged roof – visible leaks and structural wear may expose personnel to weather and injury risk.",
  "The site security cabin was found to be in poor condition. The cabin was unclean, and the furniture (chair and table) were damaged and still not replaced despite previous reports. In addition, there is no electricity supply in the cabin, creating inadequate working conditions for security personnel.",
  "It was observed that the CCTV cameras at the site security cabin are currently unserviceable. This compromises the site's overall security monitoring and incident response capability. Ref: NEOM-NPR-STD-001 - Projects Health and Safety Assurance Standards, Section 37.4: Security and Site Access Control.",
  "It was observed that the CCTV cameras were not operational during working hours"
];

function testCategory(name, observations) {
  console.log(`\n=== ${name} Test (${observations.length} observations) ===\n`);

  const factorCounts = {};
  let noFactors = 0;
  const failures = [];

  observations.forEach((obs, i) => {
    const factors = detectContributingFactors(obs);

    if (factors.length === 0) {
      noFactors++;
      failures.push({ num: i + 1, obs: obs.substring(0, 80) });
    }

    factors.forEach(f => {
      factorCounts[f] = (factorCounts[f] || 0) + 1;
    });
  });

  console.log('=== FACTOR BREAKDOWN ===');
  const sortedFactors = Object.entries(factorCounts).sort((a, b) => b[1] - a[1]);
  sortedFactors.forEach(([factor, count]) => {
    console.log(`${factor}: ${count} (${Math.round(count/observations.length*100)}%)`);
  });

  console.log('\n=== SUMMARY ===');
  console.log('Total observations:', observations.length);
  console.log('Observations with factors:', observations.length - noFactors, '(' + Math.round((observations.length - noFactors)/observations.length*100) + '%)');
  console.log('Still unclassified:', noFactors);

  if (failures.length > 0 && failures.length <= 25) {
    console.log('\n=== STILL UNCLASSIFIED (' + failures.length + ') ===');
    failures.forEach(f => {
      console.log(f.num + '. "' + f.obs + '..."');
    });
  }

  return { total: observations.length, classified: observations.length - noFactors, unclassified: noFactors };
}

// Run tests
const bbsResults = testCategory('BBS Observations in Site Security', bbsObservations);
const signageResults = testCategory('Signage Observations in Site Security', signageObservations);
const maintenanceResults = testCategory('Maintenance Observations in Site Security', maintenanceObservations);

// Combined summary
console.log('\n\n========== COMBINED SUMMARY ==========');
const totalObs = bbsResults.total + signageResults.total + maintenanceResults.total;
const totalClassified = bbsResults.classified + signageResults.classified + maintenanceResults.classified;
console.log(`Total Site Security observations: ${totalObs}`);
console.log(`Total classified: ${totalClassified} (${Math.round(totalClassified/totalObs*100)}%)`);
console.log(`Total unclassified: ${totalObs - totalClassified}`);
