const { detectContributingFactors } = require('./src/utils/rootCauseEngine.js');

// Signage Observations in Temporary Works (65 observations)
const signageObservations = [
  "Legible signage displayed and properly maintained at key areas",
  "Directional and location Safety Signage from main road entrance to office compound Al Harbi WO-050 is lacking. There is no information or guidance on the road itself to indicate site entranceway and many of the offices have no information on the doors to assist newcomers.",
  "UMC safety Team has focused on provision of warning, Information and Directional signages at site.",
  "PAPI informative banners displayed on site",
  "Safety Signages are damaged, arrange all safety signage in proper way.",
  "distrbution of instruction signboard to identify H&S roles and site precautions for all entered to site office area including visitors",
  "Additional road safety signages on MOBILE usage has been installed in dumping area.",
  "Found proper signages and demarcation installed at zone 6 access",
  "It was observed that health and safety signboards are properly installed at roundabout near the site entrance",
  "Observed the new signages regarding no use of mobile and no boots on the ground at security check point.",
  "Observed the new signages regarding no use of mobile and no boots on the ground at the entrance of the site.",
  "Directional signage to site entrance installed",
  "Good practice - Multilingual construction safety banner displayed",
  "Good practice - ELTIZAM banners displayed at key locations",
  "Project direction TDP signage found place at site main entrance.",
  "Project directional signs not provided",
  "Good practice - Site safety rule and requirement banner displayed at entrance",
  "It is observed that zone -5 is installed with proper signages adequately with the complete demarcation towards the access",
  "GOOD DIPLAY OF ELTIZAM BANNERS AT SITE",
  "Eltizam posters displayed at site",
  "Poor housekeeping around casted concrete areas, scattered shutter and wooden waste which was not removed from site. Recommendations: All unwanted and waste materials shall remove from site ensure dispose to the designated area. Ensure that de-shuttered formwork shall store in designated area ensure workplace shall keep clean and tidy.",
  "Eltizam sign board displayed at office area near PMC office",
  "Eltizam significant hazards and multilingual signboard and posters displayed at workplace. HSE Statistics board updated.",
  "good display of signages at the entrance of the working site",
  "project sign board displayed near the gate of ISF -HIDC GCS site",
  "Hindi Language signage installed at work location",
  "according to activity at the site ,permit signed by issuer and receiver and its in permit box",
  "Excavated/ Cut area edges not adequately protected, provided soil berm was not with adequate height near formwork at ISF worksite. Contractors must ensure that edge protection must be in place for all excavated. Ensure that all excavated protected with hard barriers or by soil berm with adequate height. Sufficient signage shall post in all areas.",
  "Reward and recognition sign board installed and pictures displayed for the award ceremony for the month of MAY -2024",
  "All faded and damaged warning tape and median replaced by GCS team and working on the traffic routes to ensure that are safe and secured for the designed traffic movement.",
  "No smoking sign installed on different location at office area",
  "GCS logo arrow sign to guide the project location installed on different areas of the road",
  "GCS logo with directional signage installed near PPCO fence to guide the project access",
  "NEOM Eltizam significant hazards signboards and posters displayed in multilingual signboard at ISF workplace.",
  "Eltizam significant hazards and multilingual signboard and posters displayed at workplace. HSE Statistics board updated.",
  "Eltizam significant hazards and multilingual signboard and posters displayed at workplace. HSE Statistics board updated.",
  "No Smoking signage installed in multiple location at office area to guide workers regarding no smoking zone",
  "Multi Language signage installed at different location",
  "Installing barricadion and signages at site entrance",
  "Its is Noticed That Activity Was Started Without Pre Activity Briefing In The Absence of Safety Officer Witch is Direct Violation",
  "The installation of various awareness and hazard signages in suitable locations is ongoing to keep workers informed and cautious about potential hazards. This will help ensure safety on-site by providing clear visual warnings and guidance for hazard prevention.",
  "Emergency Drill No. 03 Mr. Ahmed, a carpenter, works with the civil team, preparing formwork inside a confined space in Area 1, C07. During the task, a worker hammers wooden planks around the steel rebar in preparation for an upcoming concrete pour. Suddenly, the worker collapses inside the confined space, likely due to oxygen deficiency. The site supervisor notices the situation and immediately calls the rescue team.",
  "No suitable signage was observed on the permit box, which may lead to confusion or improper use.",
  "It was observed that the site was being arranged with adequate placement of signages and soft barriers around the site. Suggested ideas : Arrangements regarding site TMP",
  "On the site it was observed that the worker is cleaning the dirty sign board",
  "It was observed that worker is cleaning dirty sign board",
  "on the site A worker was found cleaning the dirty sign board",
  "It was noticed that during the shifting of concrete, it was not handled properly, leading to spillage on the ground.",
  "It was observed on site that workers were placing caution signs in the workplace area to indicate potential hazards and ensure awareness.",
  "Areas with low-hanging structures or obstructions were identified without proper \"Head Bump Hazard\" signage, increasing the risk of head injuries.",
  "It was noticed that during the shifting of concrete, it was not handled properly, leading to spillage on the ground.",
  "i observed that the worker was observed cleaning the dirty sign board",
  "A wooden box was observed on-site without proper identification signage.",
  "SHAR started placement of appropriate signages on site",
  "Display signboards at site",
  "To ensure safety and prevent any accidents, the de-nailing area has been secured with soft barricades. Additionally, signage has been placed to clearly indicate the hazards and inform individuals about the de-nailing activity taking place.",
  "It has been noticed the contractor is providing the site with safety signage and posts.",
  "Eltizam campaign posters displayed on site.",
  "Observed adequate material management in site lay down area with appropriate Signages.",
  "Informative signages placed at all building of Assets-2,3 & 4",
  "SHAR H&S Team provided different language \"call to action campaign\" posters at site.",
  "Fabricated stair access has been provided and signage displayed.",
  "Poor control and supervision at site where a group of workers who is working with underpass F 01 were found eating at site instead of designated dining area.",
  "It was noticed that the steel rebars was placed between the pathway. Immediately remove the rebars and clear the pathway. Pathways must be cleared and free from the obstructions.",
  "The safety signages were noted to be properly displayed at the site."
];

// Housekeeping Observations in Temporary Works (39 observations)
const housekeepingObservations = [
  "Observed site toilets are in dirty condition not been cleaning daily basis.",
  "Legible signage displayed and properly maintained at key areas",
  "No disposable glasses provided in good quantity at site having hygienic issues. Only few glasses are available at site that are being used again and again.",
  "Toilets remain unclean/ unhygienic, no water and hand wash facility provided. Repeated finding without corrective actions. Site team were advised for compliance.",
  "Portable toilet was dirty the cleaner was available and cleaned the toilet",
  "All sanitary conveniences are adequately cleaned and clear the sediments from toilets and wash basins",
  "The sanitary conveniences are not adequately cleaned, dirty and sediments are clearly seen on wash basins and toilets.",
  "It was observed that a garbage bag was full and required immediate attention, creating a hygiene and housekeeping concern.",
  "It was observed during the site inspection that the site toilet was found in poor condition. The area was unhygienic and not properly maintained, posing a potential health risk to workers.",
  "Chek some equipment Baar code good condition",
  "Poor housekeeping around casted concrete areas, scattered shutter and wooden waste which was not removed from site. Recommendations: All unwanted and waste materials shall remove from site ensure dispose to the designated area. Ensure that de-shuttered formwork shall store in designated area ensure workplace shall keep clean and tidy.",
  "During our tour we found accumulative waste near the control building consist of deferent type of used bags and wood.",
  "Multi languages urine color chart displayed in the toilet.",
  "no urine color chart displayed in the toilet",
  "Additional toilettes installed at site to meet the welfare requirements.",
  "During our site walk we observe unsafe condition - temporary materials storage area not adequately barricaded.",
  "During site inspection it was observed that the HDPE pipe waste wasn't removed by the responsible team after finishing the activity",
  "The toilet in Area 3 is out of order due to a malfunctioning flush, causing difficulties for workers.",
  "Waste polythene sheets have been collected and removed from the site for proper disposal, improving site cleanliness and promoting a sustainable environment.",
  "On the site it was observed that the worker is cleaning the dirty sign board",
  "The materials were stored improperly in the storage area, creating potential safety hazards and disorganization.",
  "It was observed that worker is cleaning dirty sign board",
  "on the site A worker was found cleaning the dirty sign board",
  "It was noticed that during the shifting of concrete, it was not handled properly, leading to spillage on the ground.",
  "During the site inspection, it was observed that a small smoking filter (cigarette butt) was found discarded on the ground, indicating non-compliance with the no-smoking policy on site.",
  "It was noticed that during the shifting of concrete, it was not handled properly, leading to spillage on the ground.",
  "Formwork has been completed, but the wooden materials were left behind in the work area, creating potential trip hazards and clutter.",
  "i observed that the worker was observed cleaning the dirty sign board",
  "Water was found to be unavailable in the toilet at the site, potentially compromising hygiene standards and causing discomfort to workers.",
  "Waste disposed.",
  "Site trash skip box with full contents not emptied to final disposal facility",
  "observed the office toilet floor was dirty.",
  "It was observed that the trash was scattered throughout the area. Immediate necessary actions are required to clear the trash from the area.",
  "It was observed that the material was scattered at working zone. Immediately remove the material.",
  "Workers portable toilets established at different locations found clean with water and hand wash facility provided.",
  "It was observed that dining room and area cleaned and tidy",
  "It was observed that the labor dining room was not cleaned and tidy. It should be cleaned and tidy.",
  "Labor dining room was observed to be clean and tidy.",
  "It was observed that equipment properly maintained 15 M distance"
];

// Environment Observations in Respiratory Hazard (231 observations)
const environmentObservations = [
  "It has been observed no dust control was provided during the night shift.",
  "Positive Observation- dust suppression doing all the site.",
  "Dust control on access routes are maintained.",
  "Doing dust suppression all the site daily basis",
  "Dust control measures maintained sitewide.",
  "Replacement of Warning tapes with poor visibility",
  "Safety signages not of standard color backgrounds and sizes. Lessons Learned = 1) Contractor to follow industry standard color prints, sizes and shapes on safety signages.",
  "Contractor failed to pay attention to dust levels, both in the working area / zone and the vicinity.",
  "Dust control measures implemented found ineffective at crusher area",
  "There are no dust control measures in placed.",
  "Dust control arrangement is provided on the site.",
  "Dust mask was not issued to operatives assigned in de-tarping activity.",
  "Inadequate dust control measures have been observed at UNIMAC access routes.",
  "No hand, eye and respiratory protection for operative assigned for cleaning cement dust.",
  "A workers is working without face shield that may lead to the lungs problem due to dust .",
  "too much dust on the NIC road because of Al Fahd earthwork and haulage activities. AL Fahd should stop haulage activities and start cleaning and sweeping the dust from the road then start dust control arrangements.",
  "It was observed that there are no standard industrial hammers with few worker it was observed that the wooden handle was crack and the top of the hammer head was loose , this could result in hammer head falling beneath and injurying workforce. Contractors to have standard industrial hammers.",
  "no dust control at the main haulage road at wadi area although the area is so dusty. ALFAHD must include arrangements for the Dust controls to protect workers and trucks from dust hazards.",
  "No job specific PPE (Goggles & respiratory protection) for operatives exposed to cement dust",
  "Excessive dust is being generated by grinding activity at Blinding Concrete area where no sufficient control measures are in place. Workers are exposed to silica dust that can travel into lungs and can cause scar tissue or cell necrosis.",
  "Dust suppression is going on to mitigate the dust issues.",
  "It is noted that contractor and Subcontractor are taking control measures on regularly, particular attention to dust levels, both in the working area / zone and the vicinity.",
  "In our commitment to safety, we employ a proactive approach to dust control by implementing water sprinkling measures across all zones. This strategy not only ensures a cleaner environment but also contributes significantly to maintaining optimal safety standards.",
  "On a daily basis, we conscientiously employ water spray for dust control, selectively targeting areas in need.",
  "Dust control implementation on hauling roads at new disposal area.",
  "Hauling road dust control",
  "Dust control at stockpiling loading area of crushed soil aggregates.",
  "No dust mask was being used while using circular saw. It will generate dust particles that are extremally dangerous for health. Usage of mask is compulsory in such situations.",
  "we are sprinkling water in all working zones for dust control measures.we are doing this activity every day while when we need it.",
  "Dust control implementation at dry soil crushing and loading area.",
  "Dust control implementation at hauling road of zone 2B.",
  "Al Fahd site dust control on daily basis",
  "Dust Control water sprinkling continue at zone 8 area",
  "Observed requied water sparay for dust control purpose on 2B road",
  "We are implementing comprehensive dust mitigation measure to ensure effetive control and supppression within the required area",
  "Water sprinkling on road to minimize the dust.",
  "Water Sprinklings on the site access road for dust control",
  "Water spraying was successfully implemented across the site, significantly reducing dust levels.",
  "It was observed that no dust control measures are being provided at the site. This absence of dust suppression can lead to increased airborne dust levels, posing health risks to workers and affecting visibility.",
  "It was observed that a cement bag was not properly covered, exposing it to moisture, dust, and potential quality degradation. This can compromise the integrity of the material.",
  "It was observed that dust accumulation was present at the site, creating potential respiratory hazards and reduced visibility.",
  "Welfare - No green netting protection against dust installed around rest area",
  "No dust control on the site",
  "No dust control was observed during the loading operation. The contractor has been advised to use water spray to control the dust.",
  "During loading use water spray fr dust control",
  "Water sprinkle found sprinkled on roads for dust control.",
  "To much dust on work side",
  "TO much dust on work side",
  "Dust Control, water spraying found on access route at zone 6.",
  "water spray fr dust control",
  "Water spray fr dust control",
  "To much dust on side",
  "Observed the dust suppression by water curing at the zone 6 access",
  "Doing water spray fr dust control all entry and exit road",
  "Doing water spray fr dust control",
  "Water spray fr dust control",
  "Dust suppression",
  "Doing water spray fr dust control all entry and exit road",
  "Doing water spray fr dust control all site",
  "Dust control water sprinkling found provided on access route in zone 4.",
  "Doing water spray fr dust control",
  "Access route found sprinkled with water near stock pile area. Dust control are in placed.",
  "No dust control in the stockpile area. Non-availability of water sprinklers at the site was evident.",
  "Doing water spray fr dust control all entry and exit road and stock pile area",
  "Dust control found provided on access routes stock pile.",
  "Water spray in stock pile area fr dust control",
  "During loading soil use water spray Dust control",
  "Observed the water curing for dust suppression at zone 4 entry access",
  "No dust control was observed during the loading operation. The contractor has been advised to use water spray to control the dust.",
  "Water spray fr dust control",
  "Observed the dust suppression by water curing at the entrance of the site.",
  "Water spray fr dust control on work side",
  "It was observed the dust suppression with water curing at the new entrance",
  "Water spray fr dust control",
  "No dust control was observed during the loading operation. The contractor has been advised to use water spray to control the dust.",
  "Doing water spray fr dust control during Dumping",
  "Dust control, water curing has been found provided on access routes zone 6.",
  "water spray fr dust control all entry and exit road",
  "Dust control water sprinkle found sprinkled over road to control the dust.",
  "water spray in stock pile area dust control",
  "Observed the dust suppression through water curing at the zone 3 roundabout near the entrance of the site.",
  "water spray fr dust control",
  "water spray fr dust control",
  "Observed dust suppression through water curing at zone 3 access.",
  "Doing water spray fr dust control",
  "During the site inspection it was observed the dust suppression through water curing on the location zone #4",
  "There was no dust control in the loading area",
  "Dust supression is not carried out on internal road as dust was observed on vehicle movement. Contractor is advised to do dust supression on internal roads",
  "Doing water spray fr dust control",
  "During the site inspection it was observed dust suppression through water curing at the location zone 5",
  "It was observed dust suppression through water curing at zone 5 access",
  "It was observed that a trailer was sprinkling water, so as to suppress dust through water curing at zone 2 entry access towards the site",
  "During the site inspection it was observed a dust suppression through water curing at zone 4 entrance",
  "water spray to control dust at site on daily basis",
  "it was observed a dust control was done by the contractor to control dust in office area",
  "dust control in parking area at laydown offices",
  "Regular dust control provided at office as worker are working for temporary facilities",
  "Daily dust control by spraying water at laydown and site to control the amount of dust.",
  "dust control done at site to control the amount of dust omission by spraying water",
  "regular dust control monitored at site",
  "daily dust control done by spraying water at site",
  "daily water spray has been done to control dust at site",
  "Dust control observed at site by spraying water to avoid health issue",
  "It was observed that dust controlled by continuous suppression of water in all working zones.",
  "dust control observed by spraying water on roads",
  "Due to traffic there is dust emission.",
  "Dust control done at site by spraying water",
  "water spraying at site for Dust Control.",
  "To minimize the generated dust from the site, the water tank starts spraying the water for dust control.",
  "Water spraying at site by tanker to control the dust",
  "Dust suppression done at office area",
  "implementing dust control at site , spraying water for all dusty area .",
  "Dust suppression system implemented at site and laydown area.",
  "Water is used for dust suppression at ISF job site to effectively binds dust particles together, making them heavier and preventing them from becoming airborne. This helps in controlling dust and improving air quality, which is crucial for maintaining a safe and healthy working environment.",
  "Dust control regular done on access road",
  "It was noticed that the dust control measures were not adequately enforced to minimize dust in the ISF workplace. The supervisor was notified and advised that water shall use was to suppress and reduce the dust levels.",
  "Dust control at site in process to eliminate the dust amount generated from movements.",
  "Access road under dust control process",
  "Dust controlled done near the security gate at site",
  "Dust control at site with water spraying",
  "To minimize the generated dust at site, dust control performed by construction team.",
  "dust controlled at site by spraying water to avoid any health issue due to dust",
  "Dust control in process at the project main road.",
  "Spraying water by tanker for dust control at site",
  "We carry out dust control at site",
  "Dust control implemented at site.",
  "During site visit, it was observed that dust control measures not effectively implemented to reduce dust near welfare facilities. Contractor shall ensure that continuous water is used to reduce and control, and area supervisor shall ensure that dust control measures are implemented.",
  "Water spraying in the Ambulance parking area , dust control .",
  "these is internal access road for the site dusty, there is no dust control .",
  "Dust mask has been provided for the operative ,who is working in the dusty area .",
  "Regular dust control by spraying water at site was observed",
  "Dust controlled by continuous suppression of water in all working zones. Traffic routes are maintained.",
  "Dust control conducted at site to reduce dust generated by normal movement.",
  "Dust control implemented at site to reduce dust generated by vehicle movement.",
  "Water spraying at site to control the dust .",
  "It was noticed that the dust control measures were not adequately implemented to minimize dust in the ISF workplace.",
  "water spray at site to control dust",
  "Dust control implemented at site.",
  "Dust control conducted today at site",
  "It was noticed that the dust control measures were not adequately enforced to minimize dust in the ISF workplace.",
  "Regular spray of water to control dust at site was observed at site",
  "dust control done on daily basis",
  "Dust control was regularly done at site to control the emission of dust",
  "dust control done on daily basis",
  "Dust control going on at site ,spraying water at all place ,at all access road",
  "water spraying at whole site to control the dust",
  "It was noticed that the dust control measures were not adequately enforced to minimize dust in the ISF workplace. The supervisor was notified and advised that water shall use was to suppress and reduce the dust levels.",
  "During the site inspection, it was observed that water was not adequately sprayed, leading to dust accumulation on the entry road of the riprap site. This poses potential hazards such as reduced visibility, respiratory issues for workers.",
  "water spray has been carried out to controle the dust issues on the site.",
  "During the site inspection, it was observed that no dust control measures have been implemented across the site.",
  "It was observed that at the area of crusher activity it was found too much dust which pollutes the air quality and lower the vision",
  "water couring was ongoing on site to controle dust issues",
  "I observed that water spraying is ongoing to effectively reduce dust on-site",
  "water sprinkler has been going on to superess the air bone dust.",
  "Water sprinkling has been consistently carried out to suppress dust and maintain air quality on-site, ensuring a safer and cleaner working environment.",
  "water sprinkling has been ongoing to control dust issues.",
  "Observed that no dust control measures were in place during ongoing activities such as backfilling, and other construction tasks. The air quality was visibly impacted by the amount of dust being generated.",
  "water sprinkling was ongiong to supress the dust on site",
  "Water sprinkling has been ongoing to supress the airbone dust.",
  "Water spraying was in progress to reduce dust. it made environment good for workers",
  "water sprinkling for dust control at area 3.",
  "water sprinkler was ongion to controle dust issues on site.",
  "Water sprinkling for dust control at site access road.",
  "Water sprinkling & soil compaction activities are being actively carried out to effectively Control dust , reduce health risk & enhance visibility at the work site.",
  "Dust controlling in area 3.",
  "Water sprinkling ongoing for dust control in area 3.",
  "It was observed that excessive dust was present at the site. Corrective actions were implemented to mitigate the issue, and the observation has been closed out",
  "water sprinkling is ongion to controle dust issues.",
  "During windy weather, the weather station is regularly monitoring to check the conditions for any potential hazards, such as strong winds, dust storms, or unsafe working environments.",
  "It was observed that a Water sprinkling at the crusher area to reduce the dust",
  "The carpenter is working in full safety compliance, using gloves, a helmet, a face shield, and a mask to protect himself from dust and potential injuries.",
  "It was noticed that there was too much dust in the site but no water curing",
  "Water sprinkling has been consistently carried out early in the morning to control dust levels on-site and maintain a safe working environment.",
  "water sprinkling is ongoing to supress the dust activity.",
  "Dust control measures have been implemented on-site.",
  "During the site inspection, it was observed that there was no visible dust control being implemented on the worksite.",
  "The equipment was operated and no dust control, the people working around not wearing mask.",
  "During the site inspection, it was noted that no dust control measures are being implemented on the worksite.",
  "water sprinkling has been ongoing to control dust issues.",
  "water sprinkling has been going on regulary to controle the dust issues.",
  "water sprinkling has been ongoing to controle the airbone dust.",
  "There are no visible dust control measures in place at the site. There is a significant amount of dust present in the air, especially in areas where cutting, sanding, or grinding is occurring.",
  "Water sprinkling is ongoing for dust control at site Area 1.",
  "Effective dust control measures were in place throughout the site. Various areas had proper dust suppression strategies implemented, including water spraying system.",
  "water sprinkler has been ongoing to controle dust isuues on site.",
  "Water sprinkling and soil compaction are actively reducing dust, minimizing health risks, and improving visibility on-site.",
  "Excessive dust was observed in multiple work areas, especially in open ground zones and areas with vehicle movement, posing health and visibility risks.",
  "Water sprinkling has been effectively implemented for dust control in Site Area 1.",
  "during morning site inspection it was observed that the water spraying was being conducted by the responsible team to reduce the dust",
  "water sprinkling has been ongoing on the site to controle dust issues.",
  "water sprinkling has been carring out on site to supress the dust.",
  "Water spraying for dust control at area 2.",
  "Water spraying has been conducted by the team at site to reduce the dust",
  "Dust levels have been effectively controlled through water suppression.",
  "On the site it was observed that the water spraying was On going near to the topion entrance road to reduce the dust",
  "Dust control measures were effectively implemented through water suppression during work activities.",
  "On the site it was observed that the water spraying is being carried out by the responsible team to reduce the potential dust",
  "The worker performing chipping activity was observed complying with safety requirements by wearing full PPE, including a face shield, dust mask, and ear plugs.",
  "Dust suppression measures were effectively implemented at the site, helping to minimize airborne dust and improve air quality.",
  "During the backfilling activity, observed a lack of dust control measures. The operation generated significant dust, which could create health risks for workers, particularly respiratory issues, and reduce visibility in the area.",
  "Regular dust control measures are implemented on-site to minimize airborne particles and maintain a safe working environment.",
  "dust control require on site",
  "water sprinkler is ongoing to control dust issues on site.",
  "During a routine site inspection, the surface was found to be dusty, which may contribute to poor air quality and visibility issues, potentially affecting workers' health and safety.",
  "It was observed that there was excessive dust at the site. Suggested ideas : Water spraying was implemented to control the dust and reduce airborne particles.",
  "Excessive dust was observed in Area 1 and Area 2, indicating a need for dust suppression measures.",
  "water sprinkling has been caaried out on main hual road to control dust issues.",
  "Insufficient dust control on site where heavy traffic of equipment emits heavy dust.",
  "During the site inspection, dust was observed accumulating in multiple work areas, posing potential health risks and reducing visibility, especially during vehicular movement and material handling.",
  "Water sprinkling ongoing for dust control at TSF area",
  "Water sprinkling for dust control is going on at TSF area",
  "Water sprinkling for dust control is ongoing at area 3.",
  "On the site it was observed that the water spraying was being conducted at site on daily basis for reducing the dust",
  "Excessive dust was observed at the site, especially around active work areas. This condition may lead to respiratory issues for workers and reduced visibility, increasing the risk of incidents.",
  "On the site it was observed that the water spraying was observed on going to reduce the dust",
  "Effective dust control observed through regular water suppression.",
  "It has been observed poor dust control near to the crasher area.",
  "SHAR-Dust Control & Periodically Housekeeping/Cleaning of asphalt Roads",
  "Dust and noise Monitoring with control measure and dust suppression.",
  "Sprinkling of water for dust control.",
  "Found doing water spraying at site for dust suppuration",
  "PPE's (white gaggles and N95 Masks) has been provided to workers for eyes protection and for dust,",
  "Dust Control by SHAR",
  "The Dust was not properly controlled, leading to potential health hazards for workers and creating a dirty and unkempt work environment. Implement dust control measures such as regular use of dust suppression.",
  "found one worker using circular saw without dust mask.",
  "During my site visit, I observed a proactive approach to dust control through ongoing dust suppression measures.",
  "It is essential to address this observation by implementing appropriate dust control measures, such as using water sprays, dust suppression systems, or enclosing the crushing machine to minimize dust generation. Ensuring effective dust control measures while operating the crushing machine is crucial to protect the health and well-being of workers and maintain a safe working environment at the site.",
  "Poor dust control. no water being sprayed to control dust in the temporary traffic roads.",
  "A positive observation at the site was the implementation of dust suppression measures while the crushing operation was ongoing. By suppressing dust, the risk of airborne particles and potential respiratory hazards for workers is significantly reduced.",
  "It was noted that dust control measures were implemented at the site.",
  "It has been noted that dust was being controlled on the site."
];

function testCategory(name, observations) {
  console.log(`\n=== ${name} Test (${observations.length} observations) ===\n`);

  const factorCounts = {};
  let noFactors = 0;
  const failures = [];

  observations.forEach((obs, i) => {
    const factors = detectContributingFactors(obs);

    if (factors.length === 0) {
      noFactors++;
      failures.push({ num: i + 1, obs: obs.substring(0, 80) });
    }

    factors.forEach(f => {
      factorCounts[f] = (factorCounts[f] || 0) + 1;
    });
  });

  console.log('=== FACTOR BREAKDOWN ===');
  const sortedFactors = Object.entries(factorCounts).sort((a, b) => b[1] - a[1]);
  sortedFactors.forEach(([factor, count]) => {
    console.log(`${factor}: ${count} (${Math.round(count/observations.length*100)}%)`);
  });

  console.log('\n=== SUMMARY ===');
  console.log('Total observations:', observations.length);
  console.log('Observations with factors:', observations.length - noFactors, '(' + Math.round((observations.length - noFactors)/observations.length*100) + '%)');
  console.log('Still unclassified:', noFactors);

  if (failures.length > 0 && failures.length <= 30) {
    console.log('\n=== STILL UNCLASSIFIED (' + failures.length + ') ===');
    failures.forEach(f => {
      console.log(f.num + '. "' + f.obs + '..."');
    });
  }

  return { total: observations.length, classified: observations.length - noFactors, unclassified: noFactors };
}

// Run tests
const signageResults = testCategory('Signage Observations in Temporary Works', signageObservations);
const housekeepingResults = testCategory('Housekeeping Observations in Temporary Works', housekeepingObservations);
const environmentResults = testCategory('Environment Observations in Respiratory Hazard', environmentObservations);

// Combined summary
console.log('\n\n========== COMBINED SUMMARY ==========');
const totalObs = signageResults.total + housekeepingResults.total + environmentResults.total;
const totalClassified = signageResults.classified + housekeepingResults.classified + environmentResults.classified;
console.log(`Total observations: ${totalObs}`);
console.log(`Total classified: ${totalClassified} (${Math.round(totalClassified/totalObs*100)}%)`);
console.log(`Total unclassified: ${totalObs - totalClassified}`);
