/**
 * Root Cause Engine - Minimal version
 * Provides observation type classification and basic statistics
 */

// ============================================================================
// FACTOR KEYWORDS MAPPING
// ============================================================================

export const FACTOR_KEYWORDS = {
  // Permit (50+)
  permit: 'Permit',
  permits: 'Permit',
  permitted: 'Permit',
  permiting: 'Permit',
  permitting: 'Permit',
  permt: 'Permit',
  permitt: 'Permit',
  permitts: 'Permit',
  permited: 'Permit',
  permitwork: 'Permit',
  ptw: 'Permit',
  ptwwork: 'Permit',
  workpermit: 'Permit',
  workpermits: 'Permit',
  hotwork: 'Permit',
  hotworks: 'Permit',
  coldwork: 'Permit',
  coldworks: 'Permit',
  loto: 'Permit',
  lotoo: 'Permit',
  lockout: 'Permit',
  lockouts: 'Permit',
  lockedout: 'Permit',
  lockingout: 'Permit',
  tagout: 'Permit',
  tagouts: 'Permit',
  taggedout: 'Permit',
  taggingout: 'Permit',
  lototo: 'Permit',
  isolation: 'Permit',
  isolations: 'Permit',
  isolated: 'Permit',
  isolate: 'Permit',
  isolating: 'Permit',
  unisolated: 'Permit',
  deisolated: 'Permit',
  energized: 'Permit',
  energised: 'Permit',
  deenergized: 'Permit',
  deenergised: 'Permit',
  excavation: 'Permit',
  excavations: 'Permit',
  excavate: 'Permit',
  excavating: 'Permit',
  confinedspace: 'Permit',
  confinedspaces: 'Permit',
  heightpermit: 'Permit',
  heightpermits: 'Permit',
  workatpermit: 'Permit',
  radiography: 'Permit',
  breakinpermit: 'Permit',

  // Training (50+)
  training: 'Training',
  trainings: 'Training',
  trained: 'Training',
  trainer: 'Training',
  trainers: 'Training',
  trainee: 'Training',
  trainees: 'Training',
  trainin: 'Training',
  traning: 'Training',
  trianing: 'Training',
  trainning: 'Training',
  traing: 'Training',
  untrained: 'Training',
  retrained: 'Training',
  retraining: 'Training',
  crosstraining: 'Training',
  crosstrained: 'Training',
  induction: 'Training',
  inductions: 'Training',
  inducted: 'Training',
  inductee: 'Training',
  inductees: 'Training',
  inducion: 'Training',
  orientation: 'Training',
  orientations: 'Training',
  oriented: 'Training',
  orientated: 'Training',
  onboarding: 'Training',
  onboarded: 'Training',
  certified: 'Training',
  certification: 'Training',
  certifications: 'Training',
  recertified: 'Training',
  recertification: 'Training',
  uncertified: 'Training',
  certificate: 'Training',
  certificates: 'Training',
  certificated: 'Training',
  coursework: 'Training',
  courseware: 'Training',
  refresher: 'Training',
  refreshers: 'Training',
  workshop: 'Training',
  workshops: 'Training',
  seminar: 'Training',
  seminars: 'Training',
  classroom: 'Training',
  elearning: 'Training',
  ojt: 'Training',
  onthejob: 'Training',

  // Competency (50+)
  competency: 'Competency',
  competencies: 'Competency',
  competent: 'Competency',
  competance: 'Competency',
  competense: 'Competency',
  compitency: 'Competency',
  compitent: 'Competency',
  incompetent: 'Competency',
  incompetence: 'Competency',
  incompetant: 'Competency',
  qualified: 'Competency',
  qualification: 'Competency',
  qualifications: 'Competency',
  unqualified: 'Competency',
  disqualified: 'Competency',
  requalified: 'Competency',
  prequalified: 'Competency',
  qualifed: 'Competency',
  skilled: 'Competency',
  unskilled: 'Competency',
  skillset: 'Competency',
  skillsets: 'Competency',
  skills: 'Competency',
  skilful: 'Competency',
  skillful: 'Competency',
  deskilled: 'Competency',
  multiskilled: 'Competency',
  experienced: 'Competency',
  inexperienced: 'Competency',
  experience: 'Competency',
  experiences: 'Competency',
  experiance: 'Competency',
  expertise: 'Competency',
  expert: 'Competency',
  experts: 'Competency',
  proficient: 'Competency',
  proficiency: 'Competency',
  nonproficient: 'Competency',
  capable: 'Competency',
  capability: 'Competency',
  capabilities: 'Competency',
  incapable: 'Competency',
  knowledgeable: 'Competency',
  knowlegeable: 'Competency',
  knowledgable: 'Competency',
  knowledge: 'Competency',
  ability: 'Competency',
  abilities: 'Competency',
  inability: 'Competency',
  aptitude: 'Competency',

  // Documentations (50+)
  documentation: 'Documentations',
  documentations: 'Documentations',
  documented: 'Documentations',
  undocumented: 'Documentations',
  documenting: 'Documentations',
  documentaion: 'Documentations',
  documenation: 'Documentations',
  documention: 'Documentations',
  docs: 'Documentations',
  procedure: 'Documentations',
  procedures: 'Documentations',
  procedural: 'Documentations',
  proceedure: 'Documentations',
  proceedures: 'Documentations',
  procedurs: 'Documentations',
  proceduers: 'Documentations',
  sop: 'Documentations',
  sops: 'Documentations',
  swms: 'Documentations',
  swp: 'Documentations',
  ssow: 'Documentations',
  jsa: 'Documentations',
  jsas: 'Documentations',
  jha: 'Documentations',
  jhas: 'Documentations',
  jsea: 'Documentations',
  jseas: 'Documentations',
  rams: 'Documentations',
  ramss: 'Documentations',
  risk: 'Documentations',
  rissk: 'Documentations',
  riskassessment: 'Documentations',
  riskassessments: 'Documentations',
  checklist: 'Documentations',
  checklists: 'Documentations',
  checksheet: 'Documentations',
  checksheets: 'Documentations',
  paperwork: 'Documentations',
  paperworks: 'Documentations',
  logbook: 'Documentations',
  logbooks: 'Documentations',
  logsheet: 'Documentations',
  logsheets: 'Documentations',
  workinstruction: 'Documentations',
  workinstructions: 'Documentations',
  methodstatement: 'Documentations',
  methodstatements: 'Documentations',
  permit: 'Documentations',
  manual: 'Documentations',
  manuals: 'Documentations',

  // Supervision (50+)
  supervision: 'Supervision',
  supervisions: 'Supervision',
  supervisor: 'Supervision',
  supervisors: 'Supervision',
  supervised: 'Supervision',
  supervising: 'Supervision',
  supervisory: 'Supervision',
  supervison: 'Supervision',
  superviser: 'Supervision',
  supervisers: 'Supervision',
  superivision: 'Supervision',
  supervisior: 'Supervision',
  unsupervised: 'Supervision',
  undersupervised: 'Supervision',
  resupervised: 'Supervision',
  foreman: 'Supervision',
  foremans: 'Supervision',
  foremen: 'Supervision',
  forman: 'Supervision',
  formans: 'Supervision',
  overseer: 'Supervision',
  overseers: 'Supervision',
  oversee: 'Supervision',
  overseeing: 'Supervision',
  oversight: 'Supervision',
  oversights: 'Supervision',
  oversite: 'Supervision',
  watchman: 'Supervision',
  watchmen: 'Supervision',
  watchmans: 'Supervision',
  spotter: 'Supervision',
  spotters: 'Supervision',
  spotting: 'Supervision',
  spotted: 'Supervision',
  banksman: 'Supervision',
  banksmen: 'Supervision',
  banksmans: 'Supervision',
  chargehand: 'Supervision',
  chargehands: 'Supervision',
  leadhand: 'Supervision',
  leadhands: 'Supervision',
  gangboss: 'Supervision',
  gangbosses: 'Supervision',
  sitesupervisor: 'Supervision',
  shiftsupervisor: 'Supervision',
  areasupervisor: 'Supervision',
  linesupervisor: 'Supervision',
  teamsupervisor: 'Supervision',
  crewsupervisor: 'Supervision',

  // Environment (50+)
  environment: 'Environment',
  environments: 'Environment',
  environmental: 'Environment',
  enviroment: 'Environment',
  enviromental: 'Environment',
  enviornment: 'Environment',
  enviornmental: 'Environment',
  enviorment: 'Environment',
  envirnoment: 'Environment',
  weather: 'Environment',
  weathers: 'Environment',
  weathering: 'Environment',
  weathered: 'Environment',
  lighting: 'Environment',
  lightings: 'Environment',
  lighted: 'Environment',
  unlighted: 'Environment',
  poorlighting: 'Environment',
  illumination: 'Environment',
  illuminated: 'Environment',
  ventilation: 'Environment',
  ventilated: 'Environment',
  unventilated: 'Environment',
  ventilating: 'Environment',
  poorventilation: 'Environment',
  temperature: 'Environment',
  temperatures: 'Environment',
  tempurature: 'Environment',
  temprature: 'Environment',
  humidity: 'Environment',
  humid: 'Environment',
  humidty: 'Environment',
  dusty: 'Environment',
  dustyness: 'Environment',
  dust: 'Environment',
  windy: 'Environment',
  windyness: 'Environment',
  rainy: 'Environment',
  raining: 'Environment',
  visibility: 'Environment',
  visability: 'Environment',
  poorvisibility: 'Environment',
  lowvisibility: 'Environment',
  workplace: 'Environment',
  workplaces: 'Environment',
  worksite: 'Environment',
  worksites: 'Environment',
  workarea: 'Environment',
  workareas: 'Environment',
  conditions: 'Environment',
  siteconditions: 'Environment',

  // Planning (50+)
  planning: 'Planning',
  plannings: 'Planning',
  planned: 'Planning',
  planner: 'Planning',
  planners: 'Planning',
  planing: 'Planning',
  planninng: 'Planning',
  unplanned: 'Planning',
  preplanning: 'Planning',
  preplanned: 'Planning',
  preplan: 'Planning',
  preplans: 'Planning',
  misplanned: 'Planning',
  replanned: 'Planning',
  replanning: 'Planning',
  schedule: 'Planning',
  schedules: 'Planning',
  scheduled: 'Planning',
  scheduling: 'Planning',
  unscheduled: 'Planning',
  rescheduled: 'Planning',
  rescheduling: 'Planning',
  scedule: 'Planning',
  schedual: 'Planning',
  schdule: 'Planning',
  coordination: 'Planning',
  coordinated: 'Planning',
  uncoordinated: 'Planning',
  coordinating: 'Planning',
  coordinator: 'Planning',
  coordinators: 'Planning',
  coordinaton: 'Planning',
  miscoordinated: 'Planning',
  preparation: 'Planning',
  preparations: 'Planning',
  prepared: 'Planning',
  unprepared: 'Planning',
  preparing: 'Planning',
  preparedness: 'Planning',
  illprepared: 'Planning',
  workplan: 'Planning',
  workplans: 'Planning',
  taskplan: 'Planning',
  taskplans: 'Planning',
  jobplan: 'Planning',
  jobplans: 'Planning',
  safetyplan: 'Planning',
  safetyplans: 'Planning',
  methodology: 'Planning',
  sequencing: 'Planning',

  // Signage (50+)
  signage: 'Signage',
  signages: 'Signage',
  sign: 'Signage',
  signs: 'Signage',
  signed: 'Signage',
  signboard: 'Signage',
  signboards: 'Signage',
  signeage: 'Signage',
  signege: 'Signage',
  signag: 'Signage',
  nosign: 'Signage',
  nosigns: 'Signage',
  missingsign: 'Signage',
  missingsigns: 'Signage',
  label: 'Signage',
  labels: 'Signage',
  labeled: 'Signage',
  labelled: 'Signage',
  labeling: 'Signage',
  labelling: 'Signage',
  unlabeled: 'Signage',
  unlabelled: 'Signage',
  mislabeled: 'Signage',
  mislabelled: 'Signage',
  relabeled: 'Signage',
  relabelled: 'Signage',
  marking: 'Signage',
  markings: 'Signage',
  marked: 'Signage',
  unmarked: 'Signage',
  mismarked: 'Signage',
  remarked: 'Signage',
  placard: 'Signage',
  placards: 'Signage',
  placarded: 'Signage',
  unplacarded: 'Signage',
  poster: 'Signage',
  posters: 'Signage',
  posted: 'Signage',
  unposted: 'Signage',
  caution: 'Signage',
  cautionary: 'Signage',
  cautiontape: 'Signage',
  warningsign: 'Signage',
  warningsigns: 'Signage',
  dangersign: 'Signage',
  dangersigns: 'Signage',
  safetysign: 'Signage',
  safetysigns: 'Signage',
  sticker: 'Signage',
  stickers: 'Signage',

  // Barriers (50+)
  barriers: 'Barriers',
  barrier: 'Barriers',
  barier: 'Barriers',
  bariers: 'Barriers',
  barriar: 'Barriers',
  barriars: 'Barriers',
  barricade: 'Barriers',
  barricades: 'Barriers',
  barricaded: 'Barriers',
  barricading: 'Barriers',
  unbarricaded: 'Barriers',
  baricade: 'Barriers',
  baricades: 'Barriers',
  baracade: 'Barriers',
  baracades: 'Barriers',
  guardrail: 'Barriers',
  guardrails: 'Barriers',
  guardrial: 'Barriers',
  gaurdrial: 'Barriers',
  handrail: 'Barriers',
  handrails: 'Barriers',
  handrial: 'Barriers',
  railing: 'Barriers',
  railings: 'Barriers',
  railling: 'Barriers',
  fencing: 'Barriers',
  fenced: 'Barriers',
  unfenced: 'Barriers',
  fence: 'Barriers',
  fences: 'Barriers',
  fenceing: 'Barriers',
  bollard: 'Barriers',
  bollards: 'Barriers',
  bollerd: 'Barriers',
  bolards: 'Barriers',
  cone: 'Barriers',
  cones: 'Barriers',
  trafficcone: 'Barriers',
  trafficcones: 'Barriers',
  delineator: 'Barriers',
  delineators: 'Barriers',
  delinator: 'Barriers',
  delinators: 'Barriers',
  demarcation: 'Barriers',
  demarcated: 'Barriers',
  demarcating: 'Barriers',
  undemarcated: 'Barriers',
  exclusionzone: 'Barriers',
  exclusionzones: 'Barriers',
  dropzone: 'Barriers',
  dropzones: 'Barriers',

  // Inspections (50+)
  inspection: 'Inspections',
  inspections: 'Inspections',
  inspect: 'Inspections',
  inspected: 'Inspections',
  inspecting: 'Inspections',
  inspector: 'Inspections',
  inspectors: 'Inspections',
  uninspected: 'Inspections',
  reinspected: 'Inspections',
  reinspection: 'Inspections',
  preinspection: 'Inspections',
  preinspected: 'Inspections',
  inpection: 'Inspections',
  insepction: 'Inspections',
  inpsection: 'Inspections',
  ispection: 'Inspections',
  audit: 'Inspections',
  audits: 'Inspections',
  audited: 'Inspections',
  auditing: 'Inspections',
  auditor: 'Inspections',
  auditors: 'Inspections',
  unaudited: 'Inspections',
  preaudit: 'Inspections',
  reaudit: 'Inspections',
  reaudited: 'Inspections',
  walkthrough: 'Inspections',
  walkthroughs: 'Inspections',
  walkdown: 'Inspections',
  walkdowns: 'Inspections',
  walkaround: 'Inspections',
  walkarounds: 'Inspections',
  verify: 'Inspections',
  verified: 'Inspections',
  verification: 'Inspections',
  verifications: 'Inspections',
  unverified: 'Inspections',
  reverified: 'Inspections',
  examine: 'Inspections',
  examined: 'Inspections',
  examination: 'Inspections',
  examinations: 'Inspections',
  examining: 'Inspections',
  review: 'Inspections',
  reviewed: 'Inspections',
  reviewing: 'Inspections',
  safetyinspection: 'Inspections',
  siteinspection: 'Inspections',
  dailyinspection: 'Inspections',
  weeklyinspection: 'Inspections',

  // Interfaces (50+)
  interfaces: 'Interfaces',
  interface: 'Interfaces',
  interfacing: 'Interfaces',
  interfaced: 'Interfaces',
  interphase: 'Interfaces',
  interphases: 'Interfaces',
  handover: 'Interfaces',
  handovers: 'Interfaces',
  handedover: 'Interfaces',
  handingover: 'Interfaces',
  handovr: 'Interfaces',
  handoff: 'Interfaces',
  handoffs: 'Interfaces',
  handedoff: 'Interfaces',
  changeover: 'Interfaces',
  changeovers: 'Interfaces',
  changedover: 'Interfaces',
  changingover: 'Interfaces',
  transition: 'Interfaces',
  transitions: 'Interfaces',
  transitioning: 'Interfaces',
  transitioned: 'Interfaces',
  turnover: 'Interfaces',
  turnovers: 'Interfaces',
  turnedover: 'Interfaces',
  turningover: 'Interfaces',
  shiftchange: 'Interfaces',
  shiftchanges: 'Interfaces',
  shifthandover: 'Interfaces',
  shifthandovers: 'Interfaces',
  crewchange: 'Interfaces',
  crewchanges: 'Interfaces',
  crewhandover: 'Interfaces',
  reliefchange: 'Interfaces',
  reliefchanges: 'Interfaces',
  interchange: 'Interfaces',
  interchanges: 'Interfaces',
  crossover: 'Interfaces',
  crossovers: 'Interfaces',
  interteam: 'Interfaces',
  interdepartment: 'Interfaces',
  interdepartmental: 'Interfaces',
  intercompany: 'Interfaces',
  intercontractor: 'Interfaces',
  multiparty: 'Interfaces',
  simultaneousops: 'Interfaces',
  simops: 'Interfaces',
  coactivity: 'Interfaces',
  coactivities: 'Interfaces',
  overlap: 'Interfaces',
  overlapping: 'Interfaces',

  // Housekeeping (50+)
  housekeeping: 'Housekeeping',
  houskeeping: 'Housekeeping',
  houskepping: 'Housekeeping',
  housekeepng: 'Housekeeping',
  housekkeping: 'Housekeeping',
  poorhousekeeping: 'Housekeeping',
  goodhousekeeping: 'Housekeeping',
  cleanliness: 'Housekeeping',
  cleaniness: 'Housekeeping',
  cleanlness: 'Housekeeping',
  cleaner: 'Housekeeping',
  cleaners: 'Housekeeping',
  cleaning: 'Housekeeping',
  cleaned: 'Housekeeping',
  uncleaned: 'Housekeeping',
  unclean: 'Housekeeping',
  dirty: 'Housekeeping',
  dirtiness: 'Housekeeping',
  dirtyness: 'Housekeeping',
  clutter: 'Housekeeping',
  cluttered: 'Housekeeping',
  uncluttered: 'Housekeeping',
  cluttering: 'Housekeeping',
  declutter: 'Housekeeping',
  decluttered: 'Housekeeping',
  debris: 'Housekeeping',
  debri: 'Housekeeping',
  debries: 'Housekeeping',
  trash: 'Housekeeping',
  trashed: 'Housekeeping',
  trashes: 'Housekeeping',
  rubbish: 'Housekeeping',
  rubish: 'Housekeeping',
  garbage: 'Housekeeping',
  garbages: 'Housekeeping',
  waste: 'Housekeeping',
  wastes: 'Housekeeping',
  wasted: 'Housekeeping',
  messy: 'Housekeeping',
  messiness: 'Housekeeping',
  mess: 'Housekeeping',
  tidy: 'Housekeeping',
  tidiness: 'Housekeeping',
  untidy: 'Housekeeping',
  tidied: 'Housekeeping',
  orderly: 'Housekeeping',
  disorderly: 'Housekeeping',
  organized: 'Housekeeping',
  disorganized: 'Housekeeping',
  spillage: 'Housekeeping',
  spillages: 'Housekeeping',

  // BBS (50+)
  bbs: 'BBS',
  bbss: 'BBS',
  behavior: 'BBS',
  behaviors: 'BBS',
  behaviour: 'BBS',
  behaviours: 'BBS',
  behavioral: 'BBS',
  behavioural: 'BBS',
  behavor: 'BBS',
  behavors: 'BBS',
  behavour: 'BBS',
  behavours: 'BBS',
  behavier: 'BBS',
  behaviers: 'BBS',
  behaviorbased: 'BBS',
  behaviourbased: 'BBS',
  behaviorsafety: 'BBS',
  behavioursafety: 'BBS',
  safebehavior: 'BBS',
  safebehaviour: 'BBS',
  safebehaviors: 'BBS',
  safebehaviours: 'BBS',
  unsafebehavior: 'BBS',
  unsafebehaviour: 'BBS',
  unsafebehaviors: 'BBS',
  unsafebehaviours: 'BBS',
  atrisk: 'BBS',
  atrisks: 'BBS',
  atriskbehavior: 'BBS',
  atriskbehaviour: 'BBS',
  riskybehavior: 'BBS',
  riskybehaviour: 'BBS',
  safeact: 'BBS',
  safeacts: 'BBS',
  unsafeact: 'BBS',
  unsafeacts: 'BBS',
  safecondition: 'BBS',
  safeconditions: 'BBS',
  unsafecondition: 'BBS',
  unsafeconditions: 'BBS',
  nearmiss: 'BBS',
  nearmisses: 'BBS',
  nearmis: 'BBS',
  goodcatch: 'BBS',
  goodcatches: 'BBS',
  stopwork: 'BBS',
  stopworks: 'BBS',
  stopworkauthority: 'BBS',
  swa: 'BBS',
  safetyobservation: 'BBS',
  safetyobservations: 'BBS',

  // Communication (50+)
  communication: 'Communication',
  communications: 'Communication',
  communicate: 'Communication',
  communicated: 'Communication',
  communicating: 'Communication',
  communicator: 'Communication',
  communicators: 'Communication',
  comunication: 'Communication',
  communcation: 'Communication',
  communicaton: 'Communication',
  communiation: 'Communication',
  comminication: 'Communication',
  miscommunication: 'Communication',
  miscommunicated: 'Communication',
  miscommunications: 'Communication',
  poorcommunication: 'Communication',
  lackcommunication: 'Communication',
  briefing: 'Communication',
  briefings: 'Communication',
  briefed: 'Communication',
  unbriefed: 'Communication',
  rebriefed: 'Communication',
  rebriefing: 'Communication',
  debriefing: 'Communication',
  debriefed: 'Communication',
  debriefings: 'Communication',
  prebriefing: 'Communication',
  prebriefed: 'Communication',
  toolbox: 'Communication',
  toolboxes: 'Communication',
  toolboxtalk: 'Communication',
  toolboxtalks: 'Communication',
  toolboxmeeting: 'Communication',
  tbt: 'Communication',
  tbts: 'Communication',
  tailgate: 'Communication',
  tailgates: 'Communication',
  tailgatemeeting: 'Communication',
  prestart: 'Communication',
  prestarts: 'Communication',
  prestartmeeting: 'Communication',
  prejob: 'Communication',
  prejobs: 'Communication',
  prejobmeeting: 'Communication',
  informed: 'Communication',
  uninformed: 'Communication',
  misinformed: 'Communication',
  notinformed: 'Communication',
  radio: 'Communication',
  radios: 'Communication',
  twowayradio: 'Communication',

  // PPE (50+)
  ppe: 'PPE',
  ppes: 'PPE',
  ppee: 'PPE',
  pppe: 'PPE',
  noppe: 'PPE',
  lackppe: 'PPE',
  missingppe: 'PPE',
  incorrectppe: 'PPE',
  wrongppe: 'PPE',
  helmet: 'PPE',
  helmets: 'PPE',
  helment: 'PPE',
  helments: 'PPE',
  hardhat: 'PPE',
  hardhats: 'PPE',
  hardhet: 'PPE',
  safetyhelmet: 'PPE',
  safetyhelmets: 'PPE',
  gloves: 'PPE',
  glove: 'PPE',
  glovs: 'PPE',
  glovess: 'PPE',
  safetygloves: 'PPE',
  workgloves: 'PPE',
  goggles: 'PPE',
  goggle: 'PPE',
  gogle: 'PPE',
  gogles: 'PPE',
  safetygoggles: 'PPE',
  glasses: 'PPE',
  safetyglasses: 'PPE',
  safetyglass: 'PPE',
  eyewear: 'PPE',
  eyeware: 'PPE',
  eyeprotection: 'PPE',
  harness: 'PPE',
  harnesses: 'PPE',
  harnes: 'PPE',
  harneses: 'PPE',
  fullharness: 'PPE',
  bodyharness: 'PPE',
  safetyharness: 'PPE',
  lanyard: 'PPE',
  lanyards: 'PPE',
  laniard: 'PPE',
  laniards: 'PPE',
  vest: 'PPE',
  vests: 'PPE',
  safetyvest: 'PPE',
  safetyvests: 'PPE',
  hiviz: 'PPE',
  hivizs: 'PPE',
  highvis: 'PPE',
  hivis: 'PPE',
  reflective: 'PPE',
  reflectives: 'PPE',
  respirator: 'PPE',
  respirators: 'PPE',
  resprator: 'PPE',
  faceshield: 'PPE',
  faceshields: 'PPE',
  earplugs: 'PPE',
  earplug: 'PPE',
  earmuffs: 'PPE',
  earmuff: 'PPE',
  hearingprotection: 'PPE',
  boots: 'PPE',
  safetyboots: 'PPE',
  steelcap: 'PPE',
  steelcaps: 'PPE',
  steeltoe: 'PPE',
  steeltoes: 'PPE',

  // Safety Devices (50+)
  safetydevice: 'Safety Devices',
  safetydevices: 'Safety Devices',
  safetydevise: 'Safety Devices',
  safetydevises: 'Safety Devices',
  safeguard: 'Safety Devices',
  safeguards: 'Safety Devices',
  safeguarded: 'Safety Devices',
  unsafeguarded: 'Safety Devices',
  safeguarding: 'Safety Devices',
  safegaurd: 'Safety Devices',
  safegaurds: 'Safety Devices',
  alarm: 'Safety Devices',
  alarms: 'Safety Devices',
  alarmed: 'Safety Devices',
  unalarmed: 'Safety Devices',
  alarming: 'Safety Devices',
  firealarm: 'Safety Devices',
  firealarms: 'Safety Devices',
  gasalarm: 'Safety Devices',
  gasalarms: 'Safety Devices',
  detector: 'Safety Devices',
  detectors: 'Safety Devices',
  detecting: 'Safety Devices',
  detected: 'Safety Devices',
  gasdetector: 'Safety Devices',
  gasdetectors: 'Safety Devices',
  smokedetector: 'Safety Devices',
  smokedetectors: 'Safety Devices',
  sensor: 'Safety Devices',
  sensors: 'Safety Devices',
  sensing: 'Safety Devices',
  sensored: 'Safety Devices',
  interlock: 'Safety Devices',
  interlocks: 'Safety Devices',
  interlocked: 'Safety Devices',
  interlocking: 'Safety Devices',
  interlocker: 'Safety Devices',
  safetyinterlock: 'Safety Devices',
  failsafe: 'Safety Devices',
  failsafes: 'Safety Devices',
  failsafed: 'Safety Devices',
  estop: 'Safety Devices',
  estops: 'Safety Devices',
  emergencystop: 'Safety Devices',
  emergencystops: 'Safety Devices',
  shutoff: 'Safety Devices',
  shutoffs: 'Safety Devices',
  autoshutoff: 'Safety Devices',
  cutoff: 'Safety Devices',
  cutoffs: 'Safety Devices',
  tripwire: 'Safety Devices',
  tripwires: 'Safety Devices',
  lightcurtain: 'Safety Devices',
  lightcurtains: 'Safety Devices',
  pressuremat: 'Safety Devices',
  pressuremats: 'Safety Devices',

  // Emergency Preparedness (50+)
  emergency: 'Emergency Preparedness',
  emergencies: 'Emergency Preparedness',
  emergancy: 'Emergency Preparedness',
  emergancys: 'Emergency Preparedness',
  emergencys: 'Emergency Preparedness',
  emergncy: 'Emergency Preparedness',
  emergeny: 'Emergency Preparedness',
  nonemergency: 'Emergency Preparedness',
  evacuation: 'Emergency Preparedness',
  evacuations: 'Emergency Preparedness',
  evacuate: 'Emergency Preparedness',
  evacuated: 'Emergency Preparedness',
  evacuating: 'Emergency Preparedness',
  evacuee: 'Emergency Preparedness',
  evacuees: 'Emergency Preparedness',
  evacation: 'Emergency Preparedness',
  evaucation: 'Emergency Preparedness',
  muster: 'Emergency Preparedness',
  musters: 'Emergency Preparedness',
  mustering: 'Emergency Preparedness',
  mustered: 'Emergency Preparedness',
  musterpoint: 'Emergency Preparedness',
  musterpoints: 'Emergency Preparedness',
  musterstation: 'Emergency Preparedness',
  musterstations: 'Emergency Preparedness',
  assembly: 'Emergency Preparedness',
  assemblys: 'Emergency Preparedness',
  assemblypoint: 'Emergency Preparedness',
  assemblypoints: 'Emergency Preparedness',
  assemblyarea: 'Emergency Preparedness',
  assemblyareas: 'Emergency Preparedness',
  firstaid: 'Emergency Preparedness',
  firstaids: 'Emergency Preparedness',
  firstaider: 'Emergency Preparedness',
  firstaiders: 'Emergency Preparedness',
  firstaidkit: 'Emergency Preparedness',
  firstaidkits: 'Emergency Preparedness',
  extinguisher: 'Emergency Preparedness',
  extinguishers: 'Emergency Preparedness',
  extinguisher: 'Emergency Preparedness',
  extingusher: 'Emergency Preparedness',
  fireextinguisher: 'Emergency Preparedness',
  fireextinguishers: 'Emergency Preparedness',
  rescue: 'Emergency Preparedness',
  rescues: 'Emergency Preparedness',
  rescuer: 'Emergency Preparedness',
  rescuers: 'Emergency Preparedness',
  rescuing: 'Emergency Preparedness',
  rescued: 'Emergency Preparedness',
  rescueteam: 'Emergency Preparedness',
  rescueteams: 'Emergency Preparedness',
  ert: 'Emergency Preparedness',
  emergencyresponse: 'Emergency Preparedness',
  emergencyresponseteam: 'Emergency Preparedness',
  drill: 'Emergency Preparedness',
  drills: 'Emergency Preparedness',
  firedrill: 'Emergency Preparedness',
  firedrills: 'Emergency Preparedness',

  // Leadership (50+)
  leadership: 'Leadership',
  leaderships: 'Leadership',
  leader: 'Leadership',
  leaders: 'Leadership',
  leading: 'Leadership',
  leadrship: 'Leadership',
  leadeship: 'Leadership',
  leardership: 'Leadership',
  poorleadership: 'Leadership',
  lackleadership: 'Leadership',
  management: 'Leadership',
  managements: 'Leadership',
  manager: 'Leadership',
  managers: 'Leadership',
  managing: 'Leadership',
  managment: 'Leadership',
  managemnt: 'Leadership',
  managerial: 'Leadership',
  mismanagement: 'Leadership',
  mismanaged: 'Leadership',
  accountability: 'Leadership',
  accountabilities: 'Leadership',
  accountable: 'Leadership',
  unaccountable: 'Leadership',
  accountablity: 'Leadership',
  responsible: 'Leadership',
  responsibility: 'Leadership',
  responsibilities: 'Leadership',
  irresponsible: 'Leadership',
  responsibilty: 'Leadership',
  responsable: 'Leadership',
  superintendent: 'Leadership',
  superintendents: 'Leadership',
  superintendant: 'Leadership',
  superintendants: 'Leadership',
  director: 'Leadership',
  directors: 'Leadership',
  directorship: 'Leadership',
  executive: 'Leadership',
  executives: 'Leadership',
  ownership: 'Leadership',
  ownerships: 'Leadership',
  commitment: 'Leadership',
  commitments: 'Leadership',
  committed: 'Leadership',
  uncommitted: 'Leadership',
  comitment: 'Leadership',
  commitent: 'Leadership',
  governance: 'Leadership',
  governances: 'Leadership',
  stewardship: 'Leadership',

  // Maintenance (50+)
  maintenance: 'Maintenance',
  maintenace: 'Maintenance',
  maintainance: 'Maintenance',
  maintainence: 'Maintenance',
  maintenence: 'Maintenance',
  maintanance: 'Maintenance',
  maintnance: 'Maintenance',
  maintain: 'Maintenance',
  maintained: 'Maintenance',
  unmaintained: 'Maintenance',
  maintaining: 'Maintenance',
  maintainer: 'Maintenance',
  maintainers: 'Maintenance',
  poorlymaintained: 'Maintenance',
  wellmaintained: 'Maintenance',
  repair: 'Maintenance',
  repairs: 'Maintenance',
  repaired: 'Maintenance',
  repairing: 'Maintenance',
  unrepaired: 'Maintenance',
  repairable: 'Maintenance',
  unrepairable: 'Maintenance',
  repairman: 'Maintenance',
  repairmen: 'Maintenance',
  broken: 'Maintenance',
  brokenn: 'Maintenance',
  broked: 'Maintenance',
  defective: 'Maintenance',
  defect: 'Maintenance',
  defects: 'Maintenance',
  defected: 'Maintenance',
  nondefective: 'Maintenance',
  malfunction: 'Maintenance',
  malfunctions: 'Maintenance',
  malfunctioned: 'Maintenance',
  malfunctioning: 'Maintenance',
  malfonction: 'Maintenance',
  faulty: 'Maintenance',
  faultiness: 'Maintenance',
  fault: 'Maintenance',
  faults: 'Maintenance',
  faulted: 'Maintenance',
  nonfaulty: 'Maintenance',
  preventive: 'Maintenance',
  preventative: 'Maintenance',
  corrective: 'Maintenance',
  predictive: 'Maintenance',
  scheduled: 'Maintenance',
  unscheduled: 'Maintenance',
  breakdown: 'Maintenance',
  breakdowns: 'Maintenance',

  // Material Handling (50+)
  material: 'Material Handling',
  materials: 'Material Handling',
  materialhandling: 'Material Handling',
  materialshandling: 'Material Handling',
  matrial: 'Material Handling',
  matrials: 'Material Handling',
  handling: 'Material Handling',
  handled: 'Material Handling',
  handler: 'Material Handling',
  handlers: 'Material Handling',
  mishandled: 'Material Handling',
  mishandling: 'Material Handling',
  manualhandling: 'Material Handling',
  safehandling: 'Material Handling',
  lifting: 'Material Handling',
  lifted: 'Material Handling',
  lifts: 'Material Handling',
  lifter: 'Material Handling',
  lifters: 'Material Handling',
  heavylifting: 'Material Handling',
  manuallifting: 'Material Handling',
  rigging: 'Material Handling',
  rigged: 'Material Handling',
  rigger: 'Material Handling',
  riggers: 'Material Handling',
  riging: 'Material Handling',
  sling: 'Material Handling',
  slings: 'Material Handling',
  slinging: 'Material Handling',
  slinged: 'Material Handling',
  slinger: 'Material Handling',
  slingers: 'Material Handling',
  load: 'Material Handling',
  loads: 'Material Handling',
  loaded: 'Material Handling',
  loading: 'Material Handling',
  loader: 'Material Handling',
  loaders: 'Material Handling',
  unloading: 'Material Handling',
  unloaded: 'Material Handling',
  overloaded: 'Material Handling',
  overloading: 'Material Handling',
  underloaded: 'Material Handling',
  stacking: 'Material Handling',
  stacked: 'Material Handling',
  stacker: 'Material Handling',
  stackers: 'Material Handling',
  unstacking: 'Material Handling',
  storage: 'Material Handling',
  storages: 'Material Handling',
  stored: 'Material Handling',
  storing: 'Material Handling',
  hoist: 'Material Handling',
  hoists: 'Material Handling',
  hoisting: 'Material Handling',
  hoisted: 'Material Handling',

  // No Authorization (50+)
  authorization: 'No Authorization',
  authorizations: 'No Authorization',
  authorize: 'No Authorization',
  authorized: 'No Authorization',
  unauthorized: 'No Authorization',
  authorizing: 'No Authorization',
  authorisation: 'No Authorization',
  authorisations: 'No Authorization',
  authorising: 'No Authorization',
  authorised: 'No Authorization',
  unauthorised: 'No Authorization',
  authorise: 'No Authorization',
  authorizaton: 'No Authorization',
  authoriztion: 'No Authorization',
  autherization: 'No Authorization',
  reauthorized: 'No Authorization',
  reauthorised: 'No Authorization',
  preauthorized: 'No Authorization',
  preauthorised: 'No Authorization',
  permission: 'No Authorization',
  permissions: 'No Authorization',
  permitted: 'No Authorization',
  unpermitted: 'No Authorization',
  permissible: 'No Authorization',
  impermissible: 'No Authorization',
  permision: 'No Authorization',
  permisions: 'No Authorization',
  nopermission: 'No Authorization',
  withoutpermission: 'No Authorization',
  restricted: 'No Authorization',
  restriction: 'No Authorization',
  restrictions: 'No Authorization',
  unrestricted: 'No Authorization',
  restricting: 'No Authorization',
  access: 'No Authorization',
  accessed: 'No Authorization',
  accessing: 'No Authorization',
  accessible: 'No Authorization',
  inaccessible: 'No Authorization',
  noaccess: 'No Authorization',
  accessdenied: 'No Authorization',
  approval: 'No Authorization',
  approvals: 'No Authorization',
  approved: 'No Authorization',
  unapproved: 'No Authorization',
  disapproved: 'No Authorization',
  approving: 'No Authorization',
  reapproved: 'No Authorization',
  preapproved: 'No Authorization',
  noapproval: 'No Authorization',
  withoutapproval: 'No Authorization',

  // Machine Guarding (50+)
  guarding: 'Machine Guarding',
  guard: 'Machine Guarding',
  guards: 'Machine Guarding',
  guarded: 'Machine Guarding',
  unguarded: 'Machine Guarding',
  guardings: 'Machine Guarding',
  reguarded: 'Machine Guarding',
  safetygaurd: 'Machine Guarding',
  safetygaurds: 'Machine Guarding',
  safetyguard: 'Machine Guarding',
  safetyguards: 'Machine Guarding',
  machineguard: 'Machine Guarding',
  machineguards: 'Machine Guarding',
  machineguarding: 'Machine Guarding',
  beltguard: 'Machine Guarding',
  beltguards: 'Machine Guarding',
  shaftguard: 'Machine Guarding',
  shaftguards: 'Machine Guarding',
  machinery: 'Machine Guarding',
  machinerys: 'Machine Guarding',
  machinary: 'Machine Guarding',
  machine: 'Machine Guarding',
  machines: 'Machine Guarding',
  machining: 'Machine Guarding',
  machinry: 'Machine Guarding',
  rotating: 'Machine Guarding',
  rotational: 'Machine Guarding',
  rotation: 'Machine Guarding',
  rotations: 'Machine Guarding',
  rotatingparts: 'Machine Guarding',
  pinchpoint: 'Machine Guarding',
  pinchpoints: 'Machine Guarding',
  pinch: 'Machine Guarding',
  pinched: 'Machine Guarding',
  nippoint: 'Machine Guarding',
  nippoints: 'Machine Guarding',
  nip: 'Machine Guarding',
  nipped: 'Machine Guarding',
  crushpoint: 'Machine Guarding',
  crushpoints: 'Machine Guarding',
  crush: 'Machine Guarding',
  crushed: 'Machine Guarding',
  crushing: 'Machine Guarding',
  entanglement: 'Machine Guarding',
  entanglements: 'Machine Guarding',
  entangled: 'Machine Guarding',
  entangling: 'Machine Guarding',
  movingparts: 'Machine Guarding',
  movingpart: 'Machine Guarding',
  exposedparts: 'Machine Guarding',
  exposedpart: 'Machine Guarding',

  // Procurement (50+)
  procurement: 'Procurement',
  procurements: 'Procurement',
  procure: 'Procurement',
  procured: 'Procurement',
  procuring: 'Procurement',
  procurment: 'Procurement',
  procuremnt: 'Procurement',
  procurment: 'Procurement',
  purchase: 'Procurement',
  purchases: 'Procurement',
  purchased: 'Procurement',
  purchasing: 'Procurement',
  purchaser: 'Procurement',
  purchasers: 'Procurement',
  purchace: 'Procurement',
  purchaces: 'Procurement',
  supplier: 'Procurement',
  suppliers: 'Procurement',
  supplying: 'Procurement',
  supplied: 'Procurement',
  supply: 'Procurement',
  supplies: 'Procurement',
  supplychain: 'Procurement',
  supplychains: 'Procurement',
  vendor: 'Procurement',
  vendors: 'Procurement',
  vendoring: 'Procurement',
  vendored: 'Procurement',
  vender: 'Procurement',
  venders: 'Procurement',
  contractor: 'Procurement',
  contractors: 'Procurement',
  contracting: 'Procurement',
  contracted: 'Procurement',
  contractr: 'Procurement',
  subcontractor: 'Procurement',
  subcontractors: 'Procurement',
  subcontracting: 'Procurement',
  subcontracted: 'Procurement',
  subbie: 'Procurement',
  subbies: 'Procurement',
  sourcing: 'Procurement',
  sourced: 'Procurement',
  outsourcing: 'Procurement',
  outsourced: 'Procurement',
  specification: 'Procurement',
  specifications: 'Procurement',
  specs: 'Procurement',
  tender: 'Procurement',
  tenders: 'Procurement',
  tendering: 'Procurement',

  // Testing (50+)
  testing: 'Testing',
  test: 'Testing',
  tests: 'Testing',
  tested: 'Testing',
  untested: 'Testing',
  tester: 'Testing',
  testers: 'Testing',
  testng: 'Testing',
  testin: 'Testing',
  retest: 'Testing',
  retested: 'Testing',
  retesting: 'Testing',
  retests: 'Testing',
  pretest: 'Testing',
  pretested: 'Testing',
  pretesting: 'Testing',
  pretests: 'Testing',
  posttest: 'Testing',
  posttested: 'Testing',
  calibration: 'Testing',
  calibrations: 'Testing',
  calibrate: 'Testing',
  calibrated: 'Testing',
  uncalibrated: 'Testing',
  calibrating: 'Testing',
  recalibrated: 'Testing',
  recalibration: 'Testing',
  recalibrating: 'Testing',
  miscalibrated: 'Testing',
  miscalibration: 'Testing',
  calibraton: 'Testing',
  calibrater: 'Testing',
  validation: 'Testing',
  validations: 'Testing',
  validate: 'Testing',
  validated: 'Testing',
  unvalidated: 'Testing',
  validating: 'Testing',
  revalidated: 'Testing',
  revalidation: 'Testing',
  invalidated: 'Testing',
  commissioning: 'Testing',
  commissioned: 'Testing',
  decommissioned: 'Testing',
  decommissioning: 'Testing',
  recommissioned: 'Testing',
  recommissioning: 'Testing',
  precommissioning: 'Testing',
  precommissioned: 'Testing',
  functiontest: 'Testing',
  functiontests: 'Testing',
  functiontesting: 'Testing'
}

// ============================================================================
// OBSERVATION TYPE CONSTANTS
// ============================================================================

export const NEGATIVE_TYPES = [
  'Near-Miss',
  'FAC',         // First Aid Case
  'MTI',         // Medical Treatment Injury
  'LTI',         // Lost Time Injury
  'Unsafe Act',
  'Unsafe Condition',
  'Environmental',
  'Property Damage'
]

export const POSITIVE_TYPES = [
  'Safe Act',
  'Safe Condition',
  'Good Practice',
  'Positive',
  'Commendation',
  'Recognition'
]

// ============================================================================
// OBSERVATION TYPE STATISTICS
// ============================================================================

/**
 * Get observation type statistics for a specific hazard
 * @param {Array} incidents - Array of incident objects
 * @param {string} hazardName - Name of the hazard to filter by
 * @returns {Object} Statistics object with positive/negative counts
 */
export const getObservationTypeStats = (incidents, hazardName) => {
  if (!incidents || !hazardName) {
    return { total: 0, positive: { count: 0, percentage: '0' }, negative: { count: 0, percentage: '0' } }
  }

  const hazardIncidents = incidents.filter(i => i.location === hazardName)
  const total = hazardIncidents.length

  if (total === 0) {
    return { total: 0, positive: { count: 0, percentage: '0' }, negative: { count: 0, percentage: '0' } }
  }

  const positiveCount = hazardIncidents.filter(i => POSITIVE_TYPES.includes(i.type)).length
  const negativeCount = hazardIncidents.filter(i => NEGATIVE_TYPES.includes(i.type)).length

  return {
    total,
    positive: {
      count: positiveCount,
      percentage: ((positiveCount / total) * 100).toFixed(1)
    },
    negative: {
      count: negativeCount,
      percentage: ((negativeCount / total) * 100).toFixed(1)
    }
  }
}

/**
 * Aggregate root causes for a specific hazard (simplified version)
 * Returns basic counts without factor detection
 * @param {Array} incidents - Array of incident objects
 * @param {string} hazardName - Name of the hazard
 * @param {string} observationType - 'positive' or 'negative'
 * @returns {Object} Aggregated data
 */
export const aggregateRootCausesForHazard = (incidents, hazardName, observationType = 'negative') => {
  if (!incidents || !hazardName) {
    return { total: 0, breakdown: [] }
  }

  const hazardIncidents = incidents.filter(i => i.location === hazardName)
  const typeList = observationType === 'positive' ? POSITIVE_TYPES : NEGATIVE_TYPES
  const filteredIncidents = hazardIncidents.filter(i => typeList.includes(i.type))

  return {
    total: filteredIncidents.length,
    breakdown: [],
    incidents: filteredIncidents
  }
}

/**
 * Detect contributing factors from description text
 * Takes first 15 words and matches against keywords
 * @param {string} description - Observation description
 * @returns {Array} Array of matched factor display names
 */
export const detectContributingFactors = (description) => {
  if (!description || typeof description !== 'string') {
    return []
  }

  // Take first 15 words
  const words = description.trim().split(/\s+/).slice(0, 15)

  // Match against keywords
  const matchedFactors = []
  const keywords = Object.keys(FACTOR_KEYWORDS)

  for (const word of words) {
    const lowerWord = word.toLowerCase().replace(/[^a-z]/g, '')
    if (keywords.includes(lowerWord)) {
      const factorName = FACTOR_KEYWORDS[lowerWord]
      if (!matchedFactors.includes(factorName)) {
        matchedFactors.push(factorName)
      }
    }
  }

  return matchedFactors
}

/**
 * Aggregate contributing factors across all incidents
 * @param {Array} incidents - Array of incidents
 * @param {string} observationType - 'positive' or 'negative' (optional filter)
 * @returns {Object} Aggregated factor data with counts and hazard breakdowns
 */
export const aggregateContributingFactors = (incidents, observationType = null) => {
  if (!incidents || incidents.length === 0) {
    return {
      byFactor: [],
      analyzed: 0,
      total: 0
    }
  }

  // Optionally filter by observation type
  let filteredIncidents = incidents
  if (observationType === 'negative') {
    filteredIncidents = incidents.filter(i => NEGATIVE_TYPES.includes(i.type))
  } else if (observationType === 'positive') {
    filteredIncidents = incidents.filter(i => POSITIVE_TYPES.includes(i.type))
  }

  // Track factors with counts and hazard breakdowns
  const factorMap = {}

  for (const incident of filteredIncidents) {
    const factors = detectContributingFactors(incident.description)

    for (const factor of factors) {
      if (!factorMap[factor]) {
        factorMap[factor] = {
          name: factor,
          count: 0,
          hazards: {},
          incidents: []
        }
      }

      factorMap[factor].count++
      factorMap[factor].incidents.push(incident)

      // Track hazard distribution
      const hazard = incident.location || 'Unknown'
      if (!factorMap[factor].hazards[hazard]) {
        factorMap[factor].hazards[hazard] = 0
      }
      factorMap[factor].hazards[hazard]++
    }
  }

  // Convert to array and sort by count
  const byFactor = Object.values(factorMap)
    .map(f => ({
      ...f,
      hazardBreakdown: Object.entries(f.hazards)
        .map(([name, count]) => ({ name, count }))
        .sort((a, b) => b.count - a.count)
    }))
    .sort((a, b) => b.count - a.count)

  return {
    byFactor,
    analyzed: filteredIncidents.length,
    total: incidents.length
  }
}

/**
 * Detect contributing factors for a specific hazard
 * @param {Array} incidents - Array of incidents
 * @param {string} hazardName - Name of the hazard to filter by
 * @returns {Array} Array of factor objects with name and count
 */
export const detectFactorsForHazard = (incidents, hazardName) => {
  if (!incidents || !hazardName) {
    return []
  }

  // Filter incidents for this hazard
  const hazardIncidents = incidents.filter(i => i.location === hazardName)

  if (hazardIncidents.length === 0) {
    return []
  }

  // Track factor counts
  const factorCounts = {}

  for (const incident of hazardIncidents) {
    const factors = detectContributingFactors(incident.description)

    for (const factor of factors) {
      if (!factorCounts[factor]) {
        factorCounts[factor] = 0
      }
      factorCounts[factor]++
    }
  }

  // Convert to array and sort by count
  return Object.entries(factorCounts)
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count)
}

export default {
  FACTOR_KEYWORDS,
  NEGATIVE_TYPES,
  POSITIVE_TYPES,
  getObservationTypeStats,
  aggregateRootCausesForHazard,
  detectContributingFactors,
  aggregateContributingFactors,
  detectFactorsForHazard
}
