/**
 * Dictionary-Based Spell Checker - Instant, Offline, No False Positives
 * Uses a large hardcoded dictionary of common misspellings (~800 entries)
 * covering: common English words, action verbs, adjectives, construction/HSE terms
 */

import { SPELL_CHECK_WHITELIST } from './constants'

// Convert whitelist to Set for O(1) lookup
const whitelistSet = new Set(SPELL_CHECK_WHITELIST.map(w => w.toLowerCase()))

// ============================================================================
// COMPREHENSIVE MISSPELLING DICTIONARY
// Covers: Common English words, action verbs, adjectives, construction/HSE terms
// ============================================================================
const COMMON_MISSPELLINGS = {
  // === VERY COMMON ENGLISH MISSPELLINGS ===
  'accomodate': 'accommodate', 'acommodate': 'accommodate', 'accomadate': 'accommodate',
  'acheive': 'achieve', 'achive': 'achieve', 'acheiv': 'achieve',
  'accross': 'across', 'acros': 'across',
  'adress': 'address', 'adres': 'address', 'addres': 'address',
  'agressive': 'aggressive', 'agresive': 'aggressive',
  'alot': 'a lot', 'alott': 'a lot',
  'amatuer': 'amateur', 'amature': 'amateur',
  'apparant': 'apparent', 'apparrent': 'apparent', 'aparent': 'apparent',
  'arguement': 'argument', 'arguemnt': 'argument',
  'basicly': 'basically', 'basicaly': 'basically',
  'beggining': 'beginning', 'begining': 'beginning',
  'beleive': 'believe', 'belive': 'believe', 'beleave': 'believe',
  'buisness': 'business', 'busness': 'business', 'bussiness': 'business',
  'calender': 'calendar', 'calandar': 'calendar', 'calander': 'calendar',
  'catagory': 'category', 'categroy': 'category', 'catergory': 'category',
  'cemetary': 'cemetery', 'cematery': 'cemetery',
  'changable': 'changeable', 'changeable': 'changeable',
  'cheif': 'chief', 'cheaf': 'chief',
  'collegue': 'colleague', 'colleage': 'colleague', 'collaegue': 'colleague',
  'comming': 'coming', 'commming': 'coming',
  'commited': 'committed', 'comitted': 'committed', 'commiteed': 'committed',
  'comparision': 'comparison', 'comparisson': 'comparison',
  'competant': 'competent', 'compitent': 'competent',
  'completly': 'completely', 'completeley': 'completely',
  'concious': 'conscious', 'consious': 'conscious',
  'copywrite': 'copyright', 'copywright': 'copyright',
  'definately': 'definitely', 'definatly': 'definitely', 'defintely': 'definitely', 'definetly': 'definitely',
  'dependant': 'dependent', 'dependend': 'dependent',
  'desparate': 'desperate', 'despirate': 'desperate',
  'develope': 'develop', 'devlop': 'develop',
  'diffrent': 'different', 'diferent': 'different', 'differant': 'different',
  'disapoint': 'disappoint', 'dissapoint': 'disappoint', 'dissappoint': 'disappoint',
  'disapear': 'disappear', 'dissapear': 'disappear', 'disappere': 'disappear',
  'embarass': 'embarrass', 'embarras': 'embarrass', 'embaress': 'embarrass',
  'enviroment': 'environment', 'enviornment': 'environment', 'enviorment': 'environment',
  'equiped': 'equipped', 'equipted': 'equipped',
  'essencial': 'essential', 'esential': 'essential',
  'exagerate': 'exaggerate', 'exaggarate': 'exaggerate',
  'excede': 'exceed', 'exeed': 'exceed',
  'existance': 'existence', 'existense': 'existence',
  'experiance': 'experience', 'expirence': 'experience', 'expierence': 'experience',
  'explination': 'explanation', 'explaination': 'explanation',
  'familar': 'familiar', 'familliar': 'familiar',
  'finaly': 'finally', 'finially': 'finally',
  'florescent': 'fluorescent', 'flourescent': 'fluorescent',
  'foriegn': 'foreign', 'forein': 'foreign',
  'fourty': 'forty', 'fourthy': 'forty',
  'freind': 'friend', 'frend': 'friend',
  'goverment': 'government', 'govermnent': 'government', 'govenment': 'government',
  'gratefull': 'grateful', 'greatful': 'grateful',
  'gaurd': 'guard', 'gurad': 'guard',
  'guidence': 'guidance', 'guideance': 'guidance',
  'happend': 'happened', 'hapened': 'happened',
  'harrass': 'harass', 'harras': 'harass',
  'heighth': 'height', 'hieght': 'height', 'heigth': 'height', 'hight': 'height',
  'heros': 'heroes', 'heroe': 'heroes',
  'hopfully': 'hopefully', 'hopefuly': 'hopefully',
  'humourous': 'humorous', 'humerous': 'humorous',
  'hygeine': 'hygiene', 'hygene': 'hygiene', 'hygine': 'hygiene',
  'ignorence': 'ignorance',
  'imaginery': 'imaginary', 'imagenary': 'imaginary',
  'imediate': 'immediate', 'imidiate': 'immediate', 'immidiate': 'immediate',
  'immediatly': 'immediately', 'imediately': 'immediately', 'immediatley': 'immediately',
  'independant': 'independent', 'independend': 'independent',
  'indispensible': 'indispensable', 'indespensable': 'indispensable',
  'innoculate': 'inoculate',
  'inteligent': 'intelligent', 'inteligant': 'intelligent',
  'intresting': 'interesting', 'intersting': 'interesting',
  'interuption': 'interruption', 'interrupton': 'interruption',
  'irrelevent': 'irrelevant', 'irrelavent': 'irrelevant',
  'jewlery': 'jewelry', 'jewellry': 'jewelry',
  'judgement': 'judgment', 'jugement': 'judgment',
  'knowlege': 'knowledge', 'knowlede': 'knowledge', 'knowlegde': 'knowledge',
  'liason': 'liaison', 'liasion': 'liaison',
  'libary': 'library', 'libery': 'library',
  'lisence': 'license', 'liscense': 'license', 'licese': 'license',
  'lightening': 'lightning', 'lightnig': 'lightning',
  'maintenace': 'maintenance', 'maintainance': 'maintenance', 'maintanance': 'maintenance',
  'manuever': 'maneuver', 'manouver': 'maneuver',
  'millenium': 'millennium', 'milennium': 'millennium',
  'minature': 'miniature', 'miniture': 'miniature',
  'mischievious': 'mischievous', 'mischevous': 'mischievous',
  'mispell': 'misspell', 'mispel': 'misspell',
  'momento': 'memento',
  'morgage': 'mortgage', 'morgtage': 'mortgage',
  'neccessary': 'necessary', 'necesary': 'necessary', 'neccesary': 'necessary', 'necessery': 'necessary',
  'negociate': 'negotiate', 'negotate': 'negotiate',
  'neice': 'niece', 'neise': 'niece',
  'nieghbor': 'neighbor', 'nieghbour': 'neighbour', 'neigbor': 'neighbor',
  'noticable': 'noticeable', 'noticible': 'noticeable',
  'occassion': 'occasion', 'ocasion': 'occasion', 'occation': 'occasion',
  'occassionally': 'occasionally', 'occasionaly': 'occasionally',
  'occured': 'occurred', 'ocurred': 'occurred', 'occureed': 'occurred',
  'occurence': 'occurrence', 'occurrance': 'occurrence', 'occurance': 'occurrence',
  'omision': 'omission', 'ommision': 'omission', 'ommission': 'omission',
  'oportunity': 'opportunity', 'oppurtunity': 'opportunity', 'oppertunity': 'opportunity',
  'optimisitic': 'optimistic', 'optmistic': 'optimistic',
  'orignal': 'original', 'origional': 'original',
  'outragous': 'outrageous', 'outragious': 'outrageous',
  'parrallel': 'parallel', 'paralel': 'parallel', 'parralel': 'parallel',
  'particulary': 'particularly', 'particullarly': 'particularly',
  'pastime': 'pastime', 'passtime': 'pastime',
  'percieve': 'perceive', 'preceive': 'perceive',
  'performence': 'performance', 'preformance': 'performance',
  'peice': 'piece', 'peise': 'piece',
  'persistant': 'persistent', 'persistend': 'persistent',
  'personel': 'personnel', 'personell': 'personnel', 'personnell': 'personnel',
  'persue': 'pursue', 'purseu': 'pursue',
  'posession': 'possession', 'possesion': 'possession',
  'potatos': 'potatoes', 'potatoe': 'potato',
  'practise': 'practice', 'practace': 'practice',
  'preceeding': 'preceding', 'preceedng': 'preceding',
  'prefered': 'preferred', 'preffered': 'preferred', 'preferd': 'preferred',
  'presance': 'presence', 'presense': 'presence',
  'privelege': 'privilege', 'priviledge': 'privilege', 'privilige': 'privilege',
  'probaly': 'probably', 'probabley': 'probably', 'propably': 'probably',
  'procede': 'proceed', 'procced': 'proceed',
  'profesional': 'professional', 'proffesional': 'professional', 'proffessional': 'professional',
  'promis': 'promise', 'promiss': 'promise',
  'pronounciation': 'pronunciation', 'pronouncation': 'pronunciation',
  'propogate': 'propagate', 'propegate': 'propagate',
  'publically': 'publicly', 'publicaly': 'publicly',
  'quarentine': 'quarantine', 'quaranteen': 'quarantine',
  'questionaire': 'questionnaire', 'questionnare': 'questionnaire',
  'que': 'queue', 'queu': 'queue',
  'realy': 'really', 'reallly': 'really',
  'recieve': 'receive', 'recive': 'receive', 'receieve': 'receive',
  'recomend': 'recommend', 'reccommend': 'recommend', 'reccomend': 'recommend', 'recommed': 'recommend',
  'refered': 'referred', 'reffered': 'referred', 'reffererd': 'referred',
  'referance': 'reference', 'refrence': 'reference', 'referrence': 'reference',
  'relevent': 'relevant', 'relavent': 'relevant', 'relevan': 'relevant',
  'religous': 'religious', 'religius': 'religious',
  'reluctent': 'reluctant',
  'remeber': 'remember', 'remmeber': 'remember', 'rember': 'remember',
  'repitition': 'repetition', 'repeatition': 'repetition',
  'restaraunt': 'restaurant', 'resturant': 'restaurant', 'restraunt': 'restaurant',
  'rythm': 'rhythm', 'rythym': 'rhythm', 'rhythym': 'rhythm',
  'sacrafice': 'sacrifice', 'sacrifise': 'sacrifice',
  'saftey': 'safety', 'safty': 'safety', 'saefty': 'safety',
  'scedule': 'schedule', 'schedual': 'schedule', 'shedule': 'schedule',
  'scholorship': 'scholarship', 'scholaship': 'scholarship',
  'scisor': 'scissor', 'sissors': 'scissors', 'scisors': 'scissors',
  'secretery': 'secretary', 'secratary': 'secretary',
  'seize': 'seize', 'sieze': 'seize',
  'sentance': 'sentence', 'sentense': 'sentence',
  'seperate': 'separate', 'seprate': 'separate', 'seperete': 'separate', 'seperat': 'separate',
  'sergent': 'sergeant', 'sargeant': 'sergeant',
  'sevral': 'several', 'serveral': 'several',
  'shiped': 'shipped', 'shippped': 'shipped',
  'seeze': 'seize',
  'similer': 'similar', 'similiar': 'similar', 'simillar': 'similar',
  'sincerly': 'sincerely', 'sincerley': 'sincerely',
  'skilfull': 'skillful', 'skilful': 'skillful',
  'speach': 'speech', 'speetch': 'speech',
  'stoping': 'stopping', 'stoppping': 'stopping',
  'strenght': 'strength', 'stregnth': 'strength', 'strentgh': 'strength',
  'stuborn': 'stubborn', 'stubern': 'stubborn',
  'succede': 'succeed', 'suceed': 'succeed',
  'succesful': 'successful', 'successfull': 'successful', 'succesfull': 'successful',
  'sucess': 'success', 'succes': 'success',
  'sufficent': 'sufficient', 'sufficiant': 'sufficient',
  'supercede': 'supersede', 'superceed': 'supersede',
  'suprise': 'surprise', 'surprize': 'surprise', 'suprize': 'surprise',
  'surreptious': 'surreptitious', 'sureptitious': 'surreptitious',
  'surveilance': 'surveillance', 'surveylance': 'surveillance',
  'sympathy': 'sympathy', 'sympathey': 'sympathy',
  'temperture': 'temperature', 'temprature': 'temperature', 'temerature': 'temperature',
  'tendancy': 'tendency',
  'therefor': 'therefore', 'therfore': 'therefore',
  'thier': 'their', 'ther': 'their',
  'threshhold': 'threshold', 'thresold': 'threshold',
  'throughly': 'thoroughly', 'thuroughly': 'thoroughly', 'thorughly': 'thoroughly',
  'tomatos': 'tomatoes', 'tomatoe': 'tomato',
  'tommorrow': 'tomorrow', 'tomorow': 'tomorrow', 'tommorow': 'tomorrow',
  'tounge': 'tongue', 'tougue': 'tongue',
  'truely': 'truly', 'truley': 'truly',
  'tyrannosarus': 'tyrannosaurus', 'tyranosaurus': 'tyrannosaurus',
  'underate': 'underrate',
  'unfortunatly': 'unfortunately', 'unfortunatley': 'unfortunately',
  'unneccessary': 'unnecessary', 'unnecesary': 'unnecessary', 'unecessary': 'unnecessary',
  'untill': 'until', 'untl': 'until', 'util': 'until',
  'unuseual': 'unusual', 'unusaul': 'unusual',
  'useable': 'usable', 'usible': 'usable',
  'usefull': 'useful', 'usful': 'useful',
  'usualy': 'usually', 'usally': 'usually', 'ussually': 'usually',
  'vaccum': 'vacuum', 'vaccuum': 'vacuum', 'vacum': 'vacuum',
  'vegetable': 'vegetable', 'vegatable': 'vegetable',
  'vehical': 'vehicle', 'vehicel': 'vehicle', 'vehichle': 'vehicle',
  'visious': 'vicious', 'viscious': 'vicious',
  'wether': 'whether', 'wheather': 'whether',
  'wierd': 'weird', 'werid': 'weird',
  'wellfare': 'welfare', 'welfair': 'welfare',
  'wich': 'which', 'whitch': 'which',
  'withdrawl': 'withdrawal', 'withdrawel': 'withdrawal',
  'writting': 'writing', 'writeing': 'writing',
  'yeild': 'yield', 'yeald': 'yield',

  // === ACTION VERBS (commonly misspelled) ===
  'accidently': 'accidentally', 'accidentaly': 'accidentally',
  'acknowlege': 'acknowledge', 'acknowlegde': 'acknowledge',
  'adquire': 'acquire', 'aquire': 'acquire',
  'analysed': 'analyzed', 'analized': 'analyzed',
  'annouced': 'announced', 'anounced': 'announced',
  'apparantly': 'apparently', 'aparently': 'apparently',
  'approch': 'approach', 'aproach': 'approach',
  'assesed': 'assessed', 'asseseed': 'assessed',
  'atached': 'attached', 'attched': 'attached',
  'beleived': 'believed', 'belived': 'believed',
  'breif': 'brief', 'breef': 'brief',
  'canceled': 'cancelled', 'canceld': 'cancelled',
  'carryed': 'carried', 'carred': 'carried',
  'carying': 'carrying', 'carring': 'carrying',
  'cheked': 'checked', 'checkd': 'checked',
  'clasified': 'classified', 'classifed': 'classified',
  'cleard': 'cleared', 'cleaered': 'cleared',
  'colected': 'collected', 'collectd': 'collected',
  'comfirmed': 'confirmed', 'confimed': 'confirmed',
  'complited': 'completed', 'completd': 'completed',
  'comunicated': 'communicated', 'comunicatd': 'communicated',
  'conected': 'connected', 'connectd': 'connected',
  'considerd': 'considered', 'consdiered': 'considered',
  'containd': 'contained', 'contaned': 'contained',
  'continud': 'continued', 'contined': 'continued',
  'controled': 'controlled', 'controld': 'controlled',
  'corected': 'corrected', 'correctd': 'corrected',
  'coverd': 'covered', 'coverred': 'covered',
  'decded': 'decided', 'decidd': 'decided',
  'deliverd': 'delivered', 'delivred': 'delivered',
  'descibed': 'described', 'describd': 'described',
  'destoryed': 'destroyed', 'destroyd': 'destroyed',
  'developd': 'developed', 'develped': 'developed',
  'discused': 'discussed', 'discussd': 'discussed',
  'discoverd': 'discovered', 'dicovered': 'discovered',
  'displayd': 'displayed', 'dispayed': 'displayed',
  'efectly': 'effectively', 'effectivly': 'effectively',
  'encounterd': 'encountered', 'encountred': 'encountered',
  'ensurd': 'ensured', 'ensuerd': 'ensured',
  'enterd': 'entered', 'enterred': 'entered',
  'equipeed': 'equipped',
  'establishd': 'established', 'establised': 'established',
  'examind': 'examined', 'examinned': 'examined',
  'exceded': 'exceeded', 'exceedded': 'exceeded',
  'executd': 'executed', 'exectued': 'executed',
  'existd': 'existed', 'exsited': 'existed',
  'explaned': 'explained', 'explaind': 'explained',
  'failded': 'failed', 'faild': 'failed',
  'finishd': 'finished', 'finshed': 'finished',
  'fixd': 'fixed', 'fixxed': 'fixed',
  'followd': 'followed', 'follwed': 'followed',
  'fomed': 'formed', 'formmed': 'formed',
  'forwaded': 'forwarded', 'forwardd': 'forwarded',
  'gethered': 'gathered', 'gatherd': 'gathered',
  'handeld': 'handled', 'handelld': 'handled',
  'helpd': 'helped', 'helpped': 'helped',
  'identifed': 'identified', 'identifyed': 'identified',
  'ignorred': 'ignored', 'ignord': 'ignored',
  'ilustrated': 'illustrated', 'ilustraed': 'illustrated',
  'implamented': 'implemented', 'implemeted': 'implemented',
  'importd': 'imported', 'importeed': 'imported',
  'improvd': 'improved', 'improveed': 'improved',
  'includde': 'included', 'inclued': 'included',
  'increasd': 'increased', 'increassed': 'increased',
  'indicatd': 'indicated', 'indicateed': 'indicated',
  'informd': 'informed', 'informeed': 'informed',
  'inspectd': 'inspected', 'inpected': 'inspected',
  'installd': 'installed', 'instaled': 'installed',
  'instructd': 'instructed', 'instructeed': 'instructed',
  'invovled': 'involved', 'involoved': 'involved',
  'isolatd': 'isolated', 'isoleted': 'isolated',
  'isssued': 'issued', 'issud': 'issued',
  'joind': 'joined', 'joinned': 'joined',
  'keepd': 'kept', 'keept': 'kept',
  'labeld': 'labeled',
  'launchd': 'launched', 'launcheed': 'launched',
  'leand': 'leaned', 'leanned': 'leaned',
  'limitd': 'limited', 'limitted': 'limited',
  'listd': 'listed', 'listeed': 'listed',
  'locatd': 'located', 'locaeted': 'located',
  'lookd': 'looked', 'loocked': 'looked',
  'maintaind': 'maintained', 'maintaned': 'maintained',
  'managd': 'managed', 'manageed': 'managed',
  'markd': 'marked', 'markeed': 'marked',
  'measurd': 'measured', 'measuered': 'measured',
  'mentond': 'mentioned', 'mentiond': 'mentioned',
  'missd': 'missed', 'misseed': 'missed',
  'modifed': 'modified', 'modifyed': 'modified',
  'monitord': 'monitored', 'montiored': 'monitored',
  'movd': 'moved', 'moveed': 'moved',
  'notd': 'noted', 'noteed': 'noted',
  'noticd': 'noticed', 'noticeed': 'noticed',
  'observd': 'observed', 'observeed': 'observed', 'obsreved': 'observed', 'observerd': 'observed',
  'obtaind': 'obtained', 'obtaned': 'obtained',
  'occurrd': 'occurred',
  'offerd': 'offered', 'offerred': 'offered',
  'opend': 'opened', 'openned': 'opened',
  'operatd': 'operated', 'opereted': 'operated',
  'orderd': 'ordered', 'orderred': 'ordered',
  'organizd': 'organized', 'organzied': 'organized',
  'performd': 'performed', 'preformed': 'performed',
  'permited': 'permitted', 'permitedd': 'permitted',
  'placd': 'placed', 'placeed': 'placed',
  'planed': 'planned', 'plannned': 'planned',
  'pointd': 'pointed', 'pointeed': 'pointed',
  'positiond': 'positioned', 'positoned': 'positioned',
  'prepard': 'prepared', 'prepareed': 'prepared',
  'presentd': 'presented', 'presenteed': 'presented',
  'preventd': 'prevented', 'preventeed': 'prevented',
  'proceded': 'proceeded', 'procedeed': 'proceeded',
  'procesd': 'processed', 'proceseed': 'processed',
  'producd': 'produced', 'produceed': 'produced',
  'programd': 'programmed', 'programeed': 'programmed',
  'protectd': 'protected', 'protcted': 'protected',
  'provded': 'provided', 'providded': 'provided',
  'reachd': 'reached', 'reacheed': 'reached',
  'reactd': 'reacted', 'reatced': 'reacted',
  'receivd': 'received', 'recieved': 'received', 'recivd': 'received',
  'recognizd': 'recognized', 'recognzied': 'recognized',
  'recordd': 'recorded', 'recroded': 'recorded',
  'recoverd': 'recovered', 'recovred': 'recovered',
  'reducde': 'reduced', 'reducd': 'reduced',
  'refusd': 'refused', 'refussed': 'refused',
  'remaind': 'remained', 'remaned': 'remained',
  'removd': 'removed', 'removeed': 'removed',
  'repaird': 'repaired', 'repared': 'repaired',
  'repeatd': 'repeated', 'repeeted': 'repeated',
  'replacd': 'replaced', 'replaceed': 'replaced',
  'reportd': 'reported', 'repoerted': 'reported',
  'representd': 'represented', 'represetned': 'represented',
  'requestd': 'requested', 'requsted': 'requested',
  'requird': 'required', 'requried': 'required',
  'resolvd': 'resolved', 'resovled': 'resolved',
  'respondde': 'responded', 'responed': 'responded',
  'restartd': 'restarted', 'restareted': 'restarted',
  'restord': 'restored', 'resotered': 'restored',
  'restrictd': 'restricted', 'restrited': 'restricted',
  'resultd': 'resulted', 'reulsted': 'resulted',
  'returnd': 'returned', 'retuned': 'returned',
  'reveald': 'revealed', 'reveled': 'revealed',
  'reviewd': 'reviewed', 'reveiwed': 'reviewed',
  'satisfed': 'satisfied', 'satisifed': 'satisfied',
  'savd': 'saved', 'saveed': 'saved',
  'scheduld': 'scheduled', 'scehduled': 'scheduled',
  'searchd': 'searched', 'serached': 'searched',
  'securd': 'secured', 'secureed': 'secured',
  'selectd': 'selected', 'sleected': 'selected',
  'separatd': 'separated', 'seprated': 'separated',
  'servd': 'served', 'serveed': 'served',
  'shipd': 'shipped', 'shippeed': 'shipped',
  'showd': 'showed', 'showeed': 'showed',
  'signd': 'signed', 'signned': 'signed',
  'solvd': 'solved', 'sovled': 'solved',
  'sortd': 'sorted', 'sotred': 'sorted',
  'specfied': 'specified', 'specifed': 'specified',
  'startd': 'started', 'starteed': 'started',
  'statd': 'stated', 'stateed': 'stated',
  'stayd': 'stayed', 'stayeed': 'stayed',
  'stopd': 'stopped', 'stoped': 'stopped', 'stoppd': 'stopped',
  'stord': 'stored', 'storeed': 'stored',
  'studyd': 'studied', 'studed': 'studied',
  'submitd': 'submitted', 'submited': 'submitted',
  'succedd': 'succeeded', 'succedeed': 'succeeded',
  'suggestd': 'suggested', 'sugested': 'suggested',
  'supplayd': 'supplied', 'suppied': 'supplied',
  'supportd': 'supported', 'suported': 'supported',
  'supposd': 'supposed', 'suposed': 'supposed',
  'survyd': 'surveyed', 'surveyd': 'surveyed',
  'suspectd': 'suspected', 'suspeted': 'suspected',
  'switchd': 'switched', 'swtched': 'switched',
  'talkd': 'talked', 'takled': 'talked',
  'testd': 'tested', 'testeed': 'tested',
  'traind': 'trained', 'tained': 'trained',
  'transferd': 'transferred', 'transfereed': 'transferred',
  'treatd': 'treated', 'treeted': 'treated',
  'tryd': 'tried', 'tryed': 'tried',
  'turnd': 'turned', 'tunred': 'turned',
  'understod': 'understood', 'undestood': 'understood',
  'updatede': 'updated', 'updaetd': 'updated',
  'upgradde': 'upgraded', 'upgaded': 'upgraded',
  'usd': 'used', 'useed': 'used',
  'verifed': 'verified', 'verifyed': 'verified',
  'visitd': 'visited', 'visted': 'visited',
  'waitd': 'waited', 'watied': 'waited',
  'walkd': 'walked', 'wlaked': 'walked',
  'wantd': 'wanted', 'watned': 'wanted',
  'warnd': 'warned', 'wanred': 'warned',
  'washd': 'washed', 'wahsed': 'washed',
  'watchd': 'watched', 'wathced': 'watched',
  'wearig': 'wearing', 'waering': 'wearing',
  'workd': 'worked', 'wokred': 'worked',

  // === CONSTRUCTION/HSE SPECIFIC ===
  'hazzard': 'hazard', 'hazrad': 'hazard', 'hzard': 'hazard',
  'protecion': 'protection', 'protecton': 'protection', 'proection': 'protection',
  'inpsection': 'inspection', 'insepction': 'inspection', 'inspecton': 'inspection',
  'equiptment': 'equipment', 'equipement': 'equipment', 'equipmnet': 'equipment', 'euipment': 'equipment',
  'scaffoldin': 'scaffolding', 'scaffoldig': 'scaffolding', 'scafolding': 'scaffolding', 'scaffoding': 'scaffolding',
  'harnes': 'harness', 'harnees': 'harness', 'harnesss': 'harness', 'harnness': 'harness',
  'helmit': 'helmet', 'helment': 'helmet', 'hemlet': 'helmet',
  'gogle': 'goggles', 'gogles': 'goggles', 'googles': 'goggles',
  'goves': 'gloves', 'glooves': 'gloves',
  'conrete': 'concrete', 'concerte': 'concrete', 'concret': 'concrete', 'conctrete': 'concrete',
  'rienforcement': 'reinforcement', 'reinfocement': 'reinforcement', 'reinforcment': 'reinforcement',
  'cemaent': 'cement', 'cemant': 'cement', 'cment': 'cement',
  'timbar': 'timber', 'timbr': 'timber',
  'plywod': 'plywood',
  'excavaion': 'excavation', 'excavtion': 'excavation', 'excation': 'excavation', 'excavaton': 'excavation',
  'trech': 'trench', 'trensh': 'trench', 'treanch': 'trench',
  'baricade': 'barricade', 'barracade': 'barricade', 'barrricade': 'barricade', 'bariccade': 'barricade',
  'barier': 'barrier', 'barrer': 'barrier', 'barriar': 'barrier',
  'eletrical': 'electrical', 'electical': 'electrical', 'electricla': 'electrical', 'elctrical': 'electrical',
  'genrator': 'generator', 'genertor': 'generator', 'genarator': 'generator',
  'cabel': 'cable', 'calbe': 'cable', 'cabl': 'cable',
  'conexion': 'connection', 'conection': 'connection', 'connecton': 'connection',
  'crain': 'crane', 'cran': 'crane', 'craen': 'crane',
  'riggin': 'rigging', 'riging': 'rigging', 'riggging': 'rigging',
  'slign': 'sling', 'silng': 'sling',
  'hoiste': 'hoist', 'hois': 'hoist',
  'wleding': 'welding', 'weilding': 'welding', 'weldin': 'welding', 'weldng': 'welding',
  'grindng': 'grinding', 'griding': 'grinding', 'grindig': 'grinding',
  'cuting': 'cutting', 'cuttin': 'cutting', 'cutiing': 'cutting',
  'locaton': 'location', 'locaion': 'location', 'loaction': 'location',
  'aera': 'area', 'erea': 'area', 'arae': 'area',
  'boundry': 'boundary', 'boundery': 'boundary', 'boudary': 'boundary',
  'perimiter': 'perimeter', 'perimeteer': 'perimeter', 'perimter': 'perimeter',
  'confind': 'confined', 'confied': 'confined', 'confiend': 'confined',
  'faling': 'falling', 'fallin': 'falling', 'failling': 'falling',
  'sliping': 'slipping', 'slippin': 'slipping', 'slippen': 'slipping',
  'triping': 'tripping', 'trippin': 'tripping', 'trippen': 'tripping',
  'checlist': 'checklist', 'checklst': 'checklist', 'cheklist': 'checklist',
  'documnet': 'document', 'docuemnt': 'document', 'documentt': 'document',
  'certficate': 'certificate', 'certificat': 'certificate', 'certifcate': 'certificate',
  'premit': 'permit', 'permt': 'permit', 'permitt': 'permit',
  'damanged': 'damaged', 'damged': 'damaged', 'dameged': 'damaged',
  'defectve': 'defective', 'defectiv': 'defective', 'deffective': 'defective',
  'unstabel': 'unstable', 'unstabe': 'unstable', 'unstabl': 'unstable',
  'unsecurd': 'unsecured', 'unseured': 'unsecured',
  'uprotected': 'unprotected', 'unprotectd': 'unprotected', 'unproteted': 'unprotected',
  'availble': 'available', 'avaliable': 'available', 'availabe': 'available',
  'requirment': 'requirement', 'requiremnt': 'requirement', 'reqirement': 'requirement',
  'procedur': 'procedure', 'proceedure': 'procedure', 'procedue': 'procedure',
  'complient': 'compliant', 'complinat': 'compliant',

  // === ADJECTIVES ===
  'accesible': 'accessible', 'accessable': 'accessible',
  'adequat': 'adequate', 'adequete': 'adequate',
  'apropriate': 'appropriate', 'approprate': 'appropriate',
  'availible': 'available', 'avalable': 'available',
  'beautifull': 'beautiful', 'beatiful': 'beautiful',
  'carefull': 'careful', 'carful': 'careful',
  'cleane': 'clean', 'cleen': 'clean',
  'comfortible': 'comfortable', 'comfertable': 'comfortable',
  'complet': 'complete', 'compleet': 'complete',
  'consistant': 'consistent', 'consistend': 'consistent',
  'conveniant': 'convenient', 'conveneint': 'convenient',
  'corect': 'correct', 'corrrect': 'correct',
  'critcal': 'critical', 'criticle': 'critical',
  'curent': 'current', 'currrent': 'current',
  'dangerious': 'dangerous', 'dangrous': 'dangerous',
  'dificult': 'difficult', 'diffucult': 'difficult',
  'dureable': 'durable', 'durible': 'durable',
  'efective': 'effective', 'effectve': 'effective',
  'efficent': 'efficient', 'efficiant': 'efficient',
  'eligable': 'eligible', 'eligble': 'eligible',
  'excelent': 'excellent', 'excellant': 'excellent',
  'expensve': 'expensive', 'expesive': 'expensive',
  'extremly': 'extremely', 'extreemly': 'extremely',
  'fammiliar': 'familiar', 'familier': 'familiar',
  'favourate': 'favourite', 'favorate': 'favorite',
  'flexable': 'flexible', 'flexibile': 'flexible',
  'frequant': 'frequent', 'freqent': 'frequent',
  'generel': 'general', 'genral': 'general',
  'harmfull': 'harmful', 'harmul': 'harmful',
  'healthly': 'healthy', 'helthy': 'healthy',
  'helpfull': 'helpful', 'helpfll': 'helpful',
  'historicle': 'historical', 'historacle': 'historical',
  'hopefull': 'hopeful', 'hopful': 'hopeful',
  'illegle': 'illegal', 'ilegal': 'illegal',
  'imediete': 'immediate', 'immediet': 'immediate',
  'importent': 'important', 'importand': 'important',
  'imposible': 'impossible', 'impossable': 'impossible',
  'incorect': 'incorrect', 'incorrent': 'incorrect',
  'incredable': 'incredible', 'incrediable': 'incredible',
  'indipendent': 'independent',
  'ineviteble': 'inevitable', 'inevatable': 'inevitable',
  'influencial': 'influential', 'influentail': 'influential',
  'invisable': 'invisible', 'invisble': 'invisible',
  'legeal': 'legal', 'leagl': 'legal',
  'lenghty': 'lengthy', 'lenghthy': 'lengthy',
  'liabale': 'liable', 'liabel': 'liable',
  'likley': 'likely', 'likly': 'likely',
  'minimle': 'minimal', 'minimul': 'minimal',
  'naturel': 'natural', 'natral': 'natural',
  'necesarry': 'necessary',
  'negitive': 'negative', 'negatve': 'negative',
  'normaly': 'normally', 'noramlly': 'normally',
  'noticiable': 'noticeable',
  'obviouse': 'obvious', 'obvius': 'obvious',
  'oficcial': 'official', 'offical': 'official',
  'optionel': 'optional', 'optinal': 'optional',
  'originle': 'original',
  'painfull': 'painful', 'paiful': 'painful',
  'particuler': 'particular', 'paticular': 'particular',
  'patiant': 'patient', 'pateint': 'patient',
  'peacfull': 'peaceful', 'peacful': 'peaceful',
  'permanant': 'permanent', 'permenent': 'permanent',
  'persinal': 'personal',
  'physicial': 'physical', 'physcial': 'physical',
  'populer': 'popular', 'populor': 'popular',
  'positeve': 'positive', 'posative': 'positive',
  'posible': 'possible', 'possable': 'possible',
  'powerfull': 'powerful', 'poweful': 'powerful',
  'practicle': 'practical', 'practial': 'practical',
  'prefferred': 'preferred',
  'previos': 'previous', 'preivous': 'previous',
  'primaraly': 'primarily', 'primarly': 'primarily',
  'probible': 'probable', 'probabal': 'probable',
  'properley': 'properly', 'proprely': 'properly',
  'recentley': 'recently', 'recenly': 'recently',
  'reguler': 'regular', 'regualr': 'regular',
  'relativley': 'relatively', 'realtively': 'relatively',
  'relieable': 'reliable', 'relaible': 'reliable',
  'remaing': 'remaining', 'remaning': 'remaining',
  'remarkible': 'remarkable', 'remarkabel': 'remarkable',
  'resonsible': 'responsible', 'responsable': 'responsible',
  'safeley': 'safely', 'saftely': 'safely',
  'satisfactorly': 'satisfactorily', 'satisfactorely': 'satisfactorily',
  'secondery': 'secondary', 'secandary': 'secondary',
  'secuer': 'secure', 'secrue': 'secure',
  'sensative': 'sensitive', 'senstive': 'sensitive',
  'seperte': 'separate',
  'serios': 'serious', 'sereous': 'serious',
  'severley': 'severely', 'severly': 'severely',
  'significent': 'significant', 'signifcant': 'significant',
  'simpley': 'simply', 'simly': 'simply',
  'slightley': 'slightly', 'slighly': 'slightly',
  'specificaly': 'specifically', 'specificly': 'specifically',
  'standered': 'standard', 'standerd': 'standard',
  'stong': 'strong', 'srong': 'strong',
  'sturctural': 'structural', 'structral': 'structural',
  'substancial': 'substantial', 'substanial': 'substantial',
  'suitible': 'suitable', 'sutable': 'suitable',
  'suspicous': 'suspicious', 'suspicisous': 'suspicious',
  'technicaly': 'technically', 'technicly': 'technically',
  'temperary': 'temporary', 'temporery': 'temporary',
  'terrable': 'terrible', 'terriable': 'terrible',
  'thoroughley': 'thoroughly', 'thorougly': 'thoroughly',
  'totaly': 'totally', 'totallly': 'totally',
  'traditionel': 'traditional', 'traditonal': 'traditional',
  'typicaly': 'typically', 'typicly': 'typically',
  'ultimatley': 'ultimately', 'ultimatly': 'ultimately',
  'unbelivable': 'unbelievable', 'unbelieveable': 'unbelievable',
  'uncertian': 'uncertain', 'uncertein': 'uncertain',
  'uniformley': 'uniformly', 'uniformaly': 'uniformly',
  'uniquley': 'uniquely', 'uniquly': 'uniquely',
  'unlikley': 'unlikely', 'unlikly': 'unlikely',
  'unnessary': 'unnecessary',
  'unsafeley': 'unsafely', 'unsaftely': 'unsafely',
  'unusualy': 'unusually', 'unusaly': 'unusually',
  'urgant': 'urgent', 'urgend': 'urgent',
  'valueable': 'valuable', 'valuble': 'valuable',
  'variouse': 'various', 'varios': 'various',
  'visable': 'visible', 'visibile': 'visible',
  'weakley': 'weakly',
  'wideley': 'widely', 'widley': 'widely',
  'wonderfull': 'wonderful', 'wonderfil': 'wonderful',
  'worthewhile': 'worthwhile', 'worthwile': 'worthwhile',

  // === MISSPELLINGS FROM HSE EXCEL DATA ===
  'acrivity': 'activity', 'activitoes': 'activities', 'activty': 'activity',
  'airbone': 'airborne',
  'amergency': 'emergency',
  'aprticipation': 'participation',
  'barrcation': 'barricading', 'barrication': 'barricading',
  'beginz': 'begins',
  'caaried': 'carried',
  'colaboration': 'collaboration',
  'coloure': 'colour',
  'drring': 'during',
  'enought': 'enough',
  'ensur': 'ensure',
  'entenace': 'entrance',
  'excvation': 'excavation',
  'fristaid': 'first aid',
  'guidliness': 'guidelines',
  'hualege': 'haulage', 'hual': 'haul',
  'inhuries': 'injuries',
  'isuues': 'issues',
  'managment': 'management',
  'mandatary': 'mandatory',
  'mwans': 'means',
  'obsereved': 'observed',
  'ongiong': 'ongoing', 'ongion': 'ongoing',
  'oproved': 'approved',
  'phasas': 'phases',
  'precauations': 'precautions',
  'preforming': 'performing',
  'rabras': 'rebars',
  'regardingf': 'regarding', 'regardingt': 'regarding',
  'regulary': 'regularly',
  'scatterly': 'scattered',
  'seperation': 'separation',
  'sigamges': 'signages',
  'sprinkilng': 'sprinkling',
  'standeards': 'standards', 'standerds': 'standards',
  'supression': 'suppression',
  'topion': 'topic',
  'trasport': 'transport',
  'tructure': 'structure',
  'verifi': 'verify',
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Check if spell checker is ready (always true for hybrid approach)
 */
export const isSpellCheckerReady = () => true

/**
 * Initialize spell checker (no-op for hybrid approach)
 */
export const initSpellChecker = async () => Promise.resolve()

/**
 * Check a single word for misspelling
 * @returns {string|null} - Correction if misspelled, null if correct
 */
export const checkWord = (word) => {
  const cleanWord = word.toLowerCase().replace(/[^a-z]/g, '')

  // Skip empty, very short, or whitelisted
  if (!cleanWord || cleanWord.length <= 2) return null
  if (whitelistSet.has(cleanWord)) return null

  // Check hardcoded dictionary (fast O(1))
  // Note: Fuzzy matching was removed as it caused too many false positives
  // (e.g., "safety" → "safely", "fire" → "wire", "working" → "warning")
  if (COMMON_MISSPELLINGS[cleanWord]) {
    return COMMON_MISSPELLINGS[cleanWord]
  }

  return null
}

/**
 * Check all words in a text
 * @returns {Array<{word: string, correction: string}>}
 */
export const checkText = (text) => {
  if (!text) return []

  const words = text.split(/\s+/)
  const misspellings = []
  const seen = new Set() // Avoid duplicates

  for (const word of words) {
    const cleanWord = word.toLowerCase().replace(/[^a-z]/g, '')
    if (seen.has(cleanWord)) continue

    const correction = checkWord(cleanWord)
    if (correction) {
      seen.add(cleanWord)
      misspellings.push({
        word: cleanWord,
        original: word,
        correction
      })
    }
  }

  return misspellings
}

/**
 * Detect misspellings in incidents array
 * @returns {Object} - { count, records, percentage }
 */
export const detectMisspellings = (incidents) => {
  if (!incidents || incidents.length === 0) {
    return { count: 0, records: [], percentage: '0.0', isReady: true }
  }

  const recordsWithMisspellings = []

  for (const incident of incidents) {
    const description = incident.description || ''
    if (description.length < 5) continue

    const misspellings = checkText(description)

    if (misspellings.length > 0) {
      recordsWithMisspellings.push({
        id: incident.externalId || incident.id,
        date: incident.date,
        reporter: incident.reportedBy || 'Unknown',
        description,
        misspellings: misspellings.map(m => ({
          misspelled: m.word,
          correction: m.correction
        })),
        incident
      })
    }
  }

  return {
    count: recordsWithMisspellings.length,
    records: recordsWithMisspellings,
    percentage: incidents.length > 0
      ? ((recordsWithMisspellings.length / incidents.length) * 100).toFixed(1)
      : '0.0',
    isReady: true
  }
}

export default {
  isReady: isSpellCheckerReady,
  init: initSpellChecker,
  check: checkWord,
  checkText,
  detectMisspellings
}
